# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: "LabWired Test Runner"
description: "Run `labwired test` in CI, emit artifact paths, and write a GitHub Actions summary."

inputs:
  script:
    description: "Path to the LabWired test script YAML."
    required: true
  firmware:
    description: "Optional path to firmware ELF (overrides script inputs)."
    required: false
    default: ""
  system:
    description: "Optional path to system manifest YAML (overrides script inputs)."
    required: false
    default: ""
  output_dir:
    description: "Directory to write artifacts (result.json, uart.log, junit.xml)."
    required: false
    default: "out/artifacts"
  no_uart_stdout:
    description: "Disable UART echo to stdout (still captured in uart.log)."
    required: false
    default: "true"
  profile:
    description: "Cargo profile to build (`release` or `debug`)."
    required: false
    default: "release"

outputs:
  artifacts_dir:
    description: "Artifacts directory containing result.json/uart.log/junit.xml."
    value: ${{ inputs.output_dir }}
  result_json:
    description: "Path to result.json."
    value: ${{ inputs.output_dir }}/result.json
  uart_log:
    description: "Path to uart.log."
    value: ${{ inputs.output_dir }}/uart.log
  junit_xml:
    description: "Path to junit.xml."
    value: ${{ inputs.output_dir }}/junit.xml
  summary_md:
    description: "Path to summary.md (markdown snippet for reports)."
    value: ${{ steps.summary.outputs.summary_md }}
  exit_code:
    description: "Exit code from `labwired test`."
    value: ${{ steps.run.outputs.exit_code }}
  status:
    description: "Status from result.json (pass/fail/error/unknown)."
    value: ${{ steps.summary.outputs.status }}
  command:
    description: "Executed command line (best-effort)."
    value: ${{ steps.run.outputs.command }}

runs:
  using: "composite"
  steps:
    - name: Build labwired
      id: build
      shell: bash
      run: |
        set -euo pipefail
        profile="${{ inputs.profile }}"

        args=(build -p labwired-cli)
        if [ "$profile" = "release" ]; then
          args+=(--release)
          bin="target/release/labwired"
        else
          bin="target/debug/labwired"
        fi

        # Prefer reproducible builds, but degrade gracefully if the lockfile is missing/out-of-date.
        out="$(mktemp)"
        set +e
        cargo "${args[@]}" --locked 2>&1 | tee "$out"
        code=${PIPESTATUS[0]}
        set -e
        if [ "$code" -ne 0 ] && grep -q "because --locked was passed" "$out"; then
          echo "::warning::cargo build --locked failed (Cargo.lock missing/out-of-date). Retrying without --locked."
          cargo "${args[@]}"
        elif [ "$code" -ne 0 ]; then
          exit "$code"
        fi

        echo "bin=$bin" >> "$GITHUB_OUTPUT"

    - name: Run labwired test (capture exit code)
      id: run
      shell: bash
      run: |
        set -euo pipefail

        out="${{ inputs.output_dir }}"
        mkdir -p "$out"

        bin="${{ steps.build.outputs.bin }}"

        args=(test --script "${{ inputs.script }}" --output-dir "$out")
        if [ "${{ inputs.no_uart_stdout }}" = "true" ]; then
          args+=(--no-uart-stdout)
        fi
        if [ -n "${{ inputs.firmware }}" ]; then
          args+=(--firmware "${{ inputs.firmware }}")
        fi
        if [ -n "${{ inputs.system }}" ]; then
          args+=(--system "${{ inputs.system }}")
        fi

        set +e
        "$bin" "${args[@]}"
        code=$?
        set -e

        echo "exit_code=$code" >> "$GITHUB_OUTPUT"
        echo "command=$bin ${args[*]}" >> "$GITHUB_OUTPUT"

        exit 0

    - name: Write summary
      id: summary
      shell: bash
      run: |
        set -euo pipefail

        out="${{ inputs.output_dir }}"
        summary="$out/summary.md"
        result="$out/result.json"

        python3 "${{ github.action_path }}/summary.py" "$result" "$summary" "$GITHUB_OUTPUT"

        cat "$summary" >> "$GITHUB_STEP_SUMMARY" || true
