// Generated by packages/board-config/scripts/generate-playground-board-catalog.mjs.
// Source of truth: packages/playground/src/bundled-configs.ts -> pickerBoards().
// Do not edit by hand.

export interface BoardCatalogEntry {
  id: string;
  name: string;
  description: string;
  board: string;
  target: string;
  mcu_component_type: string;
}

export const PLAYGROUND_BOARD_CATALOG: BoardCatalogEntry[] = [
  {
    "id": "stm32f103-blinky",
    "name": "STM32F103 Blinky",
    "description": "Classic LED blink on Cortex-M3. Toggles PA5 via GPIO.",
    "board": "stm32f103",
    "target": "stm32f103",
    "mcu_component_type": "stm32-dev"
  },
  {
    "id": "nucleo-f401re",
    "name": "Nucleo-F401RE",
    "description": "STM32F4 Nucleo board with LED on PA5 and user button on PC13.",
    "board": "stm32f401",
    "target": "stm32f401",
    "mcu_component_type": "nucleo-f401re"
  },
  {
    "id": "stm32f401cdu6-blackpill",
    "name": "STM32F401CDU6 Black Pill",
    "description": "Compact STM32F401CDU6 Black Pill board with active-low PC13 LED.",
    "board": "stm32f401cdu6",
    "target": "stm32f401cdu6",
    "mcu_component_type": "stm32-blackpill"
  },
  {
    "id": "nucleo-h563zi",
    "name": "Nucleo-H563ZI",
    "description": "STM32H5 Nucleo-144 board with 3 LEDs and a user button.",
    "board": "stm32h563",
    "target": "stm32h563",
    "mcu_component_type": "nucleo-h563zi"
  },
  {
    "id": "esp32c3-supermini",
    "name": "ESP32-C3 Super Mini",
    "description": "Compact RISC-V ESP32-C3 Super Mini board with USB-C. Built-in user LED on GPIO8 (active-low).",
    "board": "esp32c3",
    "target": "esp32c3",
    "mcu_component_type": "esp32-c3-supermini"
  },
  {
    "id": "esp32s3-zero",
    "name": "ESP32-S3-Zero",
    "description": "Xtensa LX7 dual-core ESP32-S3 with USB-C. RGB LED on GPIO48.",
    "board": "esp32s3",
    "target": "esp32s3",
    "mcu_component_type": "esp32-s3-zero"
  },
  {
    "id": "rp2040-pico",
    "name": "Raspberry Pi Pico",
    "description": "RP2040 dual-core ARM Cortex-M0+ board.",
    "board": "rp2040",
    "target": "rp2040",
    "mcu_component_type": "rpi-pico"
  },
  {
    "id": "nrf52840-dk",
    "name": "nRF52840 DK",
    "description": "Nordic nRF52840 dev kit with BLE.",
    "board": "nrf52840",
    "target": "nrf52840",
    "mcu_component_type": "nrf52840-dk"
  }
];

export function listPlaygroundBoards(filter?: string): BoardCatalogEntry[] {
  if (!filter) return PLAYGROUND_BOARD_CATALOG;
  const q = filter.toLowerCase();
  return PLAYGROUND_BOARD_CATALOG.filter((board) =>
    [board.id, board.name, board.description, board.board, board.target, board.mcu_component_type]
      .some((value) => value.toLowerCase().includes(q)),
  );
}

export function getPlaygroundBoard(id: string): BoardCatalogEntry | undefined {
  return PLAYGROUND_BOARD_CATALOG.find((board) => board.id === id);
}
