// LabWired - Firmware Simulation Platform
// Copyright (C) 2026 Andrii Shylenko
//
// This software is released under the MIT License.
// See the LICENSE file in the project root for full license information.

//! Generates the fixture's `memory.x` from the environment.
//!
//! The perf gate has to link the same spin loop against every memory map in
//! the board matrix, not just the STM32 one: nRF and Kinetis put flash at
//! 0x00000000, the RP2xxx parts at 0x10000000, and MKW41Z4 puts RAM at
//! 0x1FFF8000. A single checked-in `memory.x` is what limited the gate to the
//! STM32 boards and left nine chips unmeasured, so the origins are inputs.
//!
//! `scripts/perf/board_perf.py` derives the values it passes here from the
//! chip descriptors themselves, so a chip whose map no fixture covers is a
//! hard error there rather than a silent gap.

use std::env;
use std::fs;
use std::path::PathBuf;

// The STM32 map, i.e. what the gate measured before it grew other fixtures.
const DEFAULT_FLASH_ORIGIN: &str = "0x08000000";
const DEFAULT_RAM_ORIGIN: &str = "0x20000000";

// Sized for the SMALLEST board in the matrix, not for any one chip: the reset
// stack pointer sits at the end of the claimed RAM, so claiming more than a
// board models faults before main() on that board.
const FLASH_LENGTH: &str = "32K";
const RAM_LENGTH: &str = "8K";

fn main() {
    let flash =
        env::var("LABWIRED_PERF_FLASH_ORIGIN").unwrap_or_else(|_| DEFAULT_FLASH_ORIGIN.to_string());
    let ram =
        env::var("LABWIRED_PERF_RAM_ORIGIN").unwrap_or_else(|_| DEFAULT_RAM_ORIGIN.to_string());

    let memory_x = format!(
        "/* Generated by build.rs — edit the origins via \
         LABWIRED_PERF_FLASH_ORIGIN / LABWIRED_PERF_RAM_ORIGIN. */\n\
         MEMORY\n\
         {{\n  \
         FLASH : ORIGIN = {flash}, LENGTH = {FLASH_LENGTH}\n  \
         RAM : ORIGIN = {ram}, LENGTH = {RAM_LENGTH}\n\
         }}\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("memory.x"), memory_x).unwrap();
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rustc-link-arg=-Tlink.x");
    println!("cargo:rerun-if-env-changed=LABWIRED_PERF_FLASH_ORIGIN");
    println!("cargo:rerun-if-env-changed=LABWIRED_PERF_RAM_ORIGIN");
}
