name: "esp32c3-nokia5110-workshop"
chip: "../chips/esp32c3.yaml"
cpu_hz: 160_000_000

external_devices:
  - id: "lcd"
    type: "pcd8544"
    connection: "spi2"
    config:
      cs_pin: "GPIO10"
      dc_pin: "GPIO2"

board_io:
  - id: "lcd"
    kind: "spi_device"
    peripheral: "spi2"
    pin: 10
    signal: "input"
    active_high: true
    device_type: "pcd8544"
