/**
 * TypeScript wrapper around the WasmSimulator bindgen API.
 * Provides typed access to the simulation engine running in WASM.
 */

export interface BoardIoBinding {
  id: string;
  kind: 'led' | 'button' | 'adc_input' | 'pwm_output' | 'i2c_device' | 'spi_device';
  peripheral: string;
  pin: number;
  signal: 'output' | 'input';
  active_high: boolean;
  i2c_address?: number;
  device_type?: string;
}

export interface BoardIoState {
  id: string;
  active: boolean;
}

export interface AnalogState {
  id: string;
  kind: 'adc_input' | 'pwm_output';
  value?: number;
  active?: boolean;
}

export interface I2cSensorState {
  id: string;
  kind: 'adxl345';
  x: number;
  y: number;
  z: number;
}

export interface PeripheralInfo {
  name: string;
  base_address: string;
}

export interface SimulatorConfig {
  systemYaml: string;
  chipYaml: string;
  firmware: Uint8Array;
}

/**
 * Raw WASM module interface (generated by wasm-bindgen).
 * This matches the exported API from labwired-wasm.
 */
export interface WasmSimulatorInstance {
  // Constructors
  new(firmware: Uint8Array): WasmSimulatorInstance;

  // Config-driven constructor
  // (static method on the module, not on instance)

  // Simulation
  step(cycles: number): void;
  step_single(): void;
  step_batch(max_cycles: number): number;

  // CPU state
  get_pc(): number;
  get_register(id: number): number;
  get_register_names(): string[];
  get_disassembly(): string;

  // Memory
  read_memory(addr: number, len: number): Uint8Array;

  // Legacy
  get_led_state(): boolean;

  // Board IO
  get_board_io_config(): BoardIoBinding[];
  get_board_io_states(): BoardIoState[];
  set_board_io_input(id: string, active: boolean): void;

  // UART
  drain_uart_output(): Uint8Array;
  feed_uart_input(data: Uint8Array): void;

  // ADC / Analog
  set_adc_value(peripheral_name: string, value: number): void;
  get_board_io_analog_states(): AnalogState[];

  // I2C sensors
  set_i2c_sensor_sample(device_id: string, x: number, y: number, z: number): void;
  get_i2c_sensor_states(): I2cSensorState[];

  // Peripherals
  get_peripheral_snapshot(name: string): unknown;
  get_peripheral_list(): PeripheralInfo[];

  // GDB
  gdb_process_packet(data: Uint8Array): Uint8Array;

  // Destructor
  free(): void;
}

export interface WasmModule {
  default: (input?: RequestInfo | URL) => Promise<void>;
  WasmSimulator: {
    new(firmware: Uint8Array): WasmSimulatorInstance;
    new_from_config(
      system_yaml: string,
      chip_yaml: string,
      firmware: Uint8Array,
    ): WasmSimulatorInstance;
  };
}

export class SimulatorBridge {
  private sim: WasmSimulatorInstance;
  private _cycles = 0;

  private constructor(sim: WasmSimulatorInstance) {
    this.sim = sim;
  }

  /** Initialize from YAML config + firmware ELF bytes. */
  static async fromConfig(
    wasmModule: WasmModule,
    config: SimulatorConfig,
  ): Promise<SimulatorBridge> {
    const sim = wasmModule.WasmSimulator.new_from_config(
      config.systemYaml,
      config.chipYaml,
      config.firmware,
    );
    return new SimulatorBridge(sim);
  }

  /** Initialize with legacy hardcoded board (backward compat). */
  static async fromFirmware(
    wasmModule: WasmModule,
    firmware: Uint8Array,
  ): Promise<SimulatorBridge> {
    const sim = new wasmModule.WasmSimulator(firmware);
    return new SimulatorBridge(sim);
  }

  get totalCycles(): number {
    return this._cycles;
  }

  stepBatch(maxCycles: number): number {
    const executed = this.sim.step_batch(maxCycles);
    this._cycles += executed;
    return executed;
  }

  stepSingle(): void {
    this.sim.step_single();
    this._cycles += 1;
  }

  getPC(): number {
    return this.sim.get_pc();
  }

  getRegister(id: number): number {
    return this.sim.get_register(id);
  }

  getRegisterNames(): string[] {
    return this.sim.get_register_names();
  }

  getDisassembly(): string {
    return this.sim.get_disassembly();
  }

  readMemory(addr: number, len: number): Uint8Array {
    return this.sim.read_memory(addr, len);
  }

  getBoardIoConfig(): BoardIoBinding[] {
    return this.sim.get_board_io_config();
  }

  getBoardIoStates(): BoardIoState[] {
    return this.sim.get_board_io_states();
  }

  setBoardIoInput(id: string, active: boolean): void {
    this.sim.set_board_io_input(id, active);
  }

  drainUartOutput(): Uint8Array {
    return this.sim.drain_uart_output();
  }

  feedUartInput(text: string): void {
    this.sim.feed_uart_input(new TextEncoder().encode(text));
  }

  setAdcValue(peripheral: string, value: number): void {
    this.sim.set_adc_value(peripheral, value);
  }

  getAnalogStates(): AnalogState[] {
    return this.sim.get_board_io_analog_states() ?? [];
  }

  setI2cSensorSample(deviceId: string, x: number, y: number, z: number): void {
    this.sim.set_i2c_sensor_sample(deviceId, x, y, z);
  }

  getI2cSensorStates(): I2cSensorState[] {
    return this.sim.get_i2c_sensor_states() ?? [];
  }

  getPeripheralSnapshot(name: string): unknown {
    return this.sim.get_peripheral_snapshot(name);
  }

  getPeripheralList(): PeripheralInfo[] {
    return this.sim.get_peripheral_list();
  }

  /** Legacy: hardcoded LED state for backward compat. */
  getLedState(): boolean {
    return this.sim.get_led_state();
  }

  dispose(): void {
    this.sim.free();
  }
}
