/**
 * TypeScript wrapper around the WasmSimulator bindgen API.
 * Provides typed access to the simulation engine running in WASM.
 */

export interface BoardIoBinding {
  id: string;
  kind: 'led' | 'button' | 'adc_input' | 'pwm_output' | 'i2c_device' | 'spi_device';
  peripheral: string;
  pin: number;
  signal: 'output' | 'input';
  active_high: boolean;
  i2c_address?: number;
  device_type?: string;
}

export interface BoardIoState {
  id: string;
  active: boolean;
}

export interface AnalogState {
  id: string;
  kind: 'adc_input' | 'pwm_output';
  value?: number;
  active?: boolean;
}

export interface I2cSensorStateAdxl345 {
  id: string;
  kind: 'adxl345';
  x: number;
  y: number;
  z: number;
}

export interface I2cSensorStateMpu6050 {
  id: string;
  kind: 'mpu6050';
  ax: number;
  ay: number;
  az: number;
  gx: number;
  gy: number;
  gz: number;
}

export interface I2cSensorStateBme280 {
  id: string;
  kind: 'bme280';
  temperature_c: number;
  humidity_pct: number;
  pressure_hpa: number;
}

export type I2cSensorState = I2cSensorStateAdxl345 | I2cSensorStateMpu6050 | I2cSensorStateBme280;

export interface SpiDeviceStateMax31855 {
  id: string;
  kind: 'max31855';
  tc_c: number;
  internal_c: number;
}

export type SpiDeviceState = SpiDeviceStateMax31855;

export interface UartDeviceStateNeo6mGps {
  id: string;
  kind: 'neo6m-gps';
  lat: number;
  lon: number;
  has_fix: boolean;
}

export type UartDeviceState = UartDeviceStateNeo6mGps;

export interface AdcDeviceStateNtcThermistor {
  id: string;
  kind: 'ntc-thermistor';
  divider_mv: number;
  adc_count: number;
}

export type AdcDeviceState = AdcDeviceStateNtcThermistor;

export interface PeripheralInfo {
  name: string;
  base_address: string;
}

export interface SimulatorConfig {
  systemYaml: string;
  chipYaml: string;
  firmware: Uint8Array;
}

/**
 * Raw WASM module interface (generated by wasm-bindgen).
 * This matches the exported API from labwired-wasm.
 */
export interface WasmSimulatorInstance {
  // Constructors
  new(firmware: Uint8Array): WasmSimulatorInstance;

  // Config-driven constructor
  // (static method on the module, not on instance)

  // Simulation
  step(cycles: number): void;
  step_single(): void;
  step_batch(max_cycles: number): number;

  // Arduino-ESP32 bootstrap glue: install heap/timer/lock/Wifi/sendHello
  // thunks, fake the dual-core handshake, seed SP, etc. Idempotent — calling
  // on non-Arduino-ESP32 firmware is a no-op aside from a few SRAM byte
  // writes that the firmware doesn't read.
  install_esp32_arduino_quirks(): void;
  /** Auto-discovery counterpart for sketches whose ELF symbols are intact —
   *  resolves Arduino-ESP32 thunk PCs from the symbol table instead of
   *  hand-curated hardcoded addresses. Works for any GxEPD2 sketch (e.g.
   *  labwired-ereader) without knowing its binary layout in advance.
   *  Caller must pass the same ELF bytes that were used to construct the
   *  simulator. */
  install_arduino_esp32_quirks(elf_bytes: Uint8Array): void;
  /** @deprecated Renamed to `install_esp32_arduino_quirks`. Kept for backwards
   *  compatibility with the legacy standalone preset-PC entry point. */
  apply_agentdeck_quirks(): void;
  // Steps the firmware plus refreshes the dual-core handshake bytes every
  // ~10k cycles so the FreeRTOS scheduler sees CPU1 as "up". Returns
  // executed cycles, same as step_batch.
  step_with_esp32_aids(max_cycles: number): number;

  // Restore the machine from a binary runtime snapshot blob (LWRS-framed
  // bincode) produced by `labwired-cli snapshot capture`. The firmware
  // must already have been loaded onto the same system manifest.
  apply_runtime_snapshot(bytes: Uint8Array): void;
  // Capture the current machine state to a runtime snapshot blob.
  take_runtime_snapshot(): Uint8Array;

  // CPU state
  get_pc(): number;
  get_register(id: number): number;
  get_register_names(): string[];
  get_disassembly(): string;

  // Memory
  read_memory(addr: number, len: number): Uint8Array;

  // Legacy
  get_led_state(): boolean;

  // Board IO
  get_board_io_config(): BoardIoBinding[];
  get_board_io_states(): BoardIoState[];
  set_board_io_input(id: string, active: boolean): void;

  // UART
  drain_uart_output(): Uint8Array;
  feed_uart_input(data: Uint8Array): void;

  // ADC / Analog
  set_adc_value(peripheral_name: string, value: number): void;
  get_board_io_analog_states(): AnalogState[];

  // I2C sensors
  set_i2c_sensor_sample(device_id: string, x: number, y: number, z: number): void;
  set_i2c_sensor_sample_6dof(device_id: string, ax: number, ay: number, az: number, gx: number, gy: number, gz: number): void;
  get_i2c_sensor_states(): I2cSensorState[];

  // SSD1306 OLED framebuffer
  get_ssd1306_framebuffer(device_id: string): Uint8Array;

  // ILI9341 TFT framebuffer
  get_ili9341_framebuffer(device_id: string): Uint8Array;

  // SSD1680 tri-color e-paper framebuffer (9472 B: 4736 black plane | 4736 red plane)
  get_ssd1680_framebuffer(device_id: string): Uint8Array;
  get_ssd1680_refresh_generation(device_id: string): number;

  // UC8151D tri-color e-paper framebuffer (same shape as SSD1680;
  // attached by install_arduino_esp32_quirks for GxEPD2 sketches).
  get_uc8151d_framebuffer(device_id: string): Uint8Array;
  get_uc8151d_refresh_generation(device_id: string): number;

  // SPI devices
  get_spi_device_states(): SpiDeviceState[];
  set_max31855_temperature(device_id: string, tc_c: number, internal_c: number): void;

  // UART stream devices (GPS)
  set_gps_position(device_id: string, lat: number, lon: number): void;
  set_gps_fix(device_id: string, active: boolean): void;
  get_uart_device_states(): UartDeviceState[];

  // ADC analog source devices (NTC thermistor)
  set_ntc_temperature(device_id: string, temperature_c: number): void;
  get_adc_device_states(): AdcDeviceState[];

  // Peripherals
  get_peripheral_snapshot(name: string): unknown;
  get_peripheral_list(): PeripheralInfo[];

  // GDB
  gdb_process_packet(data: Uint8Array): Uint8Array;

  // Destructor
  free(): void;
}

export interface WasmModule {
  default: (input?: RequestInfo | URL) => Promise<void>;
  WasmSimulator: {
    new(firmware: Uint8Array): WasmSimulatorInstance;
    new_from_config(
      system_yaml: string,
      chip_yaml: string,
      firmware: Uint8Array,
    ): WasmSimulatorInstance;
  };
}

export class SimulatorBridge {
  private sim: WasmSimulatorInstance;
  private _cycles = 0;
  private _esp32ArduinoQuirks = false;

  private constructor(sim: WasmSimulatorInstance) {
    this.sim = sim;
  }

  /** Whether `installEsp32ArduinoQuirks` has been invoked on this bridge. */
  get hasEsp32ArduinoQuirks(): boolean {
    return this._esp32ArduinoQuirks;
  }

  /** @deprecated Renamed to `hasEsp32ArduinoQuirks`. */
  get hasAgentdeckQuirks(): boolean {
    return this._esp32ArduinoQuirks;
  }

  /**
   * Install the Arduino-ESP32 bootstrap thunks (heap-caps, esp_timer, locks,
   * setCpuFrequencyMhz, esp_ota_*, HardwareSerial, delay, WifiWsLink::begin,
   * WifiWsLink::loop, sendHello, esp_crc8, etc.) and fake the dual-core
   * bringup handshake. Idempotent. Once applied, `stepBatch` routes through
   * `step_with_esp32_aids` so the dual-core handshake bytes stay alive across
   * iterations.
   */
  installEsp32ArduinoQuirks(): void {
    this.sim.install_esp32_arduino_quirks();
    this._esp32ArduinoQuirks = true;
  }

  /** Auto-discovery quirks installer — pass the firmware ELF bytes so
   *  thunks resolve to actual PCs from the symbol table. Use this for
   *  arbitrary GxEPD2 / Arduino-ESP32 sketches (e.g. labwired-ereader);
   *  the original `installEsp32ArduinoQuirks` uses preset-PC
   *  hardcoded PCs that won't match other binaries. */
  installArduinoEsp32QuirksAutodiscover(elfBytes: Uint8Array): void {
    this.sim.install_arduino_esp32_quirks(elfBytes);
    this._esp32ArduinoQuirks = true;
  }

  /** @deprecated Renamed to `installEsp32ArduinoQuirks`. The bootstrap is
   *  generic Arduino-ESP32 glue, not firmware-specific. */
  applyAgentdeckQuirks(): void {
    this.installEsp32ArduinoQuirks();
  }

  /**
   * Restore the machine from a binary runtime snapshot blob (LWRS magic,
   * bincode-framed). The firmware must already have been loaded onto the
   * same system manifest the snapshot was captured from — typically a
   * demo's pre-built `.lwrs` file fetched from the GitHub release that
   * hosts its ELF.
   *
   * On failure the WASM call throws; the bridge is left in an undefined
   * state and callers should treat it as a hard reset.
   */
  applyRuntimeSnapshot(bytes: Uint8Array): void {
    this.sim.apply_runtime_snapshot(bytes);
  }

  /** Capture the current machine state to a runtime snapshot blob — mirror
   * of `applyRuntimeSnapshot`. The returned bytes can be persisted (e.g.
   * `URL.createObjectURL` for download) and later fed back to
   * `applyRuntimeSnapshot` on a fresh bridge. */
  takeRuntimeSnapshot(): Uint8Array {
    return this.sim.take_runtime_snapshot();
  }

  /** Initialize from YAML config + firmware ELF bytes. */
  static async fromConfig(
    wasmModule: WasmModule,
    config: SimulatorConfig,
  ): Promise<SimulatorBridge> {
    const sim = wasmModule.WasmSimulator.new_from_config(
      config.systemYaml,
      config.chipYaml,
      config.firmware,
    );
    return new SimulatorBridge(sim);
  }

  /** Initialize with legacy hardcoded board (backward compat). */
  static async fromFirmware(
    wasmModule: WasmModule,
    firmware: Uint8Array,
  ): Promise<SimulatorBridge> {
    const sim = new wasmModule.WasmSimulator(firmware);
    return new SimulatorBridge(sim);
  }

  get totalCycles(): number {
    return this._cycles;
  }

  stepBatch(maxCycles: number): number {
    // Route ESP32-classic firmware that needs the dual-core handshake
    // refresh through the aided step function — keeps loopTask alive.
    const executed = this._esp32ArduinoQuirks
      ? this.sim.step_with_esp32_aids(maxCycles)
      : this.sim.step_batch(maxCycles);
    this._cycles += executed;
    return executed;
  }

  stepSingle(): void {
    this.sim.step_single();
    this._cycles += 1;
  }

  getPC(): number {
    return this.sim.get_pc();
  }

  getRegister(id: number): number {
    return this.sim.get_register(id);
  }

  getRegisterNames(): string[] {
    return this.sim.get_register_names();
  }

  getDisassembly(): string {
    return this.sim.get_disassembly();
  }

  readMemory(addr: number, len: number): Uint8Array {
    return this.sim.read_memory(addr, len);
  }

  getBoardIoConfig(): BoardIoBinding[] {
    return this.sim.get_board_io_config();
  }

  getBoardIoStates(): BoardIoState[] {
    return this.sim.get_board_io_states();
  }

  setBoardIoInput(id: string, active: boolean): void {
    this.sim.set_board_io_input(id, active);
  }

  drainUartOutput(): Uint8Array {
    return this.sim.drain_uart_output();
  }

  feedUartInput(text: string): void {
    this.sim.feed_uart_input(new TextEncoder().encode(text));
  }

  setAdcValue(peripheral: string, value: number): void {
    this.sim.set_adc_value(peripheral, value);
  }

  getAnalogStates(): AnalogState[] {
    return this.sim.get_board_io_analog_states() ?? [];
  }

  setI2cSensorSample(deviceId: string, x: number, y: number, z: number): void {
    this.sim.set_i2c_sensor_sample(deviceId, x, y, z);
  }

  setMpu6050Sample(deviceId: string, ax: number, ay: number, az: number, gx: number, gy: number, gz: number): void {
    this.sim.set_i2c_sensor_sample_6dof(deviceId, ax, ay, az, gx, gy, gz);
  }

  getI2cSensorStates(): I2cSensorState[] {
    return this.sim.get_i2c_sensor_states() ?? [];
  }

  getPeripheralSnapshot(name: string): unknown {
    return this.sim.get_peripheral_snapshot(name);
  }

  getPeripheralList(): PeripheralInfo[] {
    return this.sim.get_peripheral_list();
  }

  getSpiDeviceStates(): SpiDeviceState[] {
    return this.sim.get_spi_device_states() ?? [];
  }

  setMax31855Temperature(deviceId: string, tc_c: number, internal_c: number): void {
    this.sim.set_max31855_temperature(deviceId, tc_c, internal_c);
  }

  /** Set the simulated GPS position. No NMEA math here — all logic is in Rust core. */
  setGpsPosition(deviceId: string, lat: number, lon: number): void {
    this.sim.set_gps_position(deviceId, lat, lon);
  }

  /** Enable or disable the GPS fix. */
  setGpsFix(deviceId: string, active: boolean): void {
    this.sim.set_gps_fix(deviceId, active);
  }

  /** Read state of UART stream devices (GPS modules, etc.). */
  getUartDeviceStates(): UartDeviceState[] {
    return this.sim.get_uart_device_states() ?? [];
  }

  /** Set temperature on an NTC thermistor device. All Steinhart-Hart math lives in Rust core. */
  setNtcTemperature(deviceId: string, temperatureC: number): void {
    this.sim.set_ntc_temperature(deviceId, temperatureC);
  }

  /** Read state of ADC analog source devices (NTC thermistor). */
  getAdcDeviceStates(): AdcDeviceState[] {
    return this.sim.get_adc_device_states() ?? [];
  }

  /** Returns the 1024-byte GDDRAM framebuffer for an SSD1306 OLED, or null if not found. */
  getSsd1306Framebuffer(deviceId: string): Uint8Array | null {
    try {
      const fb = this.sim.get_ssd1306_framebuffer(deviceId);
      return fb ? new Uint8Array(fb) : null;
    } catch {
      return null;
    }
  }

  /** Returns the 153,600-byte RGB565 framebuffer for an ILI9341 TFT, or null if not found. */
  getIli9341Framebuffer(deviceId: string): Uint8Array | null {
    try {
      const fb = this.sim.get_ili9341_framebuffer(deviceId);
      return fb ? new Uint8Array(fb) : null;
    } catch {
      return null;
    }
  }

  /**
   * Returns the 9472-byte tri-color e-paper framebuffer for an SSD1680 panel, or null if not found.
   * Layout: first 4736 bytes = black plane (1=white/0=black), next 4736 = red plane on the wire
   * (1=no-red/0=red — GxEPD2 inverts source bitmap before sending 0x26). Row-major, 128 px wide ×
   * 296 px tall native, MSB-first within byte.
   */
  getSsd1680Framebuffer(deviceId: string): Uint8Array | null {
    try {
      const fb = this.sim.get_ssd1680_framebuffer(deviceId);
      return fb ? new Uint8Array(fb) : null;
    } catch {
      return null;
    }
  }

  /** Cheap u32 — UI uses it to poll for "did the panel refresh?" before re-fetching the full buffer. */
  getSsd1680RefreshGeneration(deviceId: string): number | null {
    try {
      return this.sim.get_ssd1680_refresh_generation(deviceId);
    } catch {
      return null;
    }
  }

  /** Same shape as SSD1680 — UC8151D panel attached by `install_arduino_esp32_quirks`. */
  getUc8151dFramebuffer(deviceId: string): Uint8Array | null {
    try {
      const fb = this.sim.get_uc8151d_framebuffer(deviceId);
      return fb ? new Uint8Array(fb) : null;
    } catch {
      return null;
    }
  }

  getUc8151dRefreshGeneration(deviceId: string): number | null {
    try {
      return this.sim.get_uc8151d_refresh_generation(deviceId);
    } catch {
      return null;
    }
  }

  /** Legacy: hardcoded LED state for backward compat. */
  getLedState(): boolean {
    return this.sim.get_led_state();
  }

  dispose(): void {
    this.sim.free();
  }
}
