schema_version: "1.0"
name: "STM32WBA52"
arch: "arm"
flash:
  base: 0x08000000
  size: "1024KB"
ram:
  base: 0x20000000
  size: "128KB"

peripherals:
  - id: "rcc"
    type: "rcc"
    base_address: 0x46020C00
    config:
      profile: "stm32v2"
  - id: "gpioa"
    type: "gpio"
    base_address: 0x42020000
    size: "1KB"
    config:
      profile: "stm32v2"
  - id: "gpiob"
    type: "gpio"
    base_address: 0x42020400
    size: "1KB"
    config:
      profile: "stm32v2"
  - id: "gpioc"
    type: "gpio"
    base_address: 0x42020800
    size: "1KB"
    config:
      profile: "stm32v2"
  - id: "gpioh"
    type: "gpio"
    base_address: 0x42021C00
    size: "1KB"
    config:
      profile: "stm32v2"
  - id: "systick"
    type: "systick"
    base_address: 0xE000E010
  - id: "lpuart1"
    type: "uart"
    base_address: 0x46002400
    irq: 45
    config:
      profile: "stm32v2"
