peripheral: WATCHDOG
version: 0.1.0
registers:
- id: CTRL
  address_offset: 0
  size: 32
  access: READ_WRITE
  reset_value: 117440512
  fields:
  - name: TIME
    bit_range:
    - 23
    - 0
    description: Indicates the number of ticks / 2 (see errata RP2040-E1) before a watchdog reset will be triggered
  - name: PAUSE_JTAG
    bit_range:
    - 24
    - 24
    description: Pause the watchdog timer when JTAG is accessing the bus fabric
  - name: PAUSE_DBG0
    bit_range:
    - 25
    - 25
    description: Pause the watchdog timer when processor 0 is in debug mode
  - name: PAUSE_DBG1
    bit_range:
    - 26
    - 26
    description: Pause the watchdog timer when processor 1 is in debug mode
  - name: ENABLE
    bit_range:
    - 30
    - 30
    description: When not enabled the watchdog timer is paused
  - name: TRIGGER
    bit_range:
    - 31
    - 31
    description: Trigger a watchdog reset
  side_effects: null
- id: LOAD
  address_offset: 4
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: LOAD
    bit_range:
    - 23
    - 0
    description: null
  side_effects: null
- id: REASON
  address_offset: 8
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: TIMER
    bit_range:
    - 0
    - 0
    description: null
  - name: FORCE
    bit_range:
    - 1
    - 1
    description: null
  side_effects: null
- id: SCRATCH0
  address_offset: 12
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH0
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: SCRATCH1
  address_offset: 16
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH1
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: SCRATCH2
  address_offset: 20
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH2
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: SCRATCH3
  address_offset: 24
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH3
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: SCRATCH4
  address_offset: 28
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH4
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: SCRATCH5
  address_offset: 32
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH5
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: SCRATCH6
  address_offset: 36
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH6
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: SCRATCH7
  address_offset: 40
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: SCRATCH7
    bit_range:
    - 31
    - 0
    description: null
  side_effects: null
- id: TICK
  address_offset: 44
  size: 32
  access: READ_WRITE
  reset_value: 512
  fields:
  - name: CYCLES
    bit_range:
    - 8
    - 0
    description: Total number of clk_tick cycles before the next tick.
  - name: ENABLE
    bit_range:
    - 9
    - 9
    description: start / stop tick generation
  - name: RUNNING
    bit_range:
    - 10
    - 10
    description: Is the tick generator running?
  - name: COUNT
    bit_range:
    - 19
    - 11
    description: 'Count down timer: the remaining number clk_tick cycles before the next tick is generated.'
  side_effects: null
interrupts: null
timing: null
