//! Generate the built-in chip registry from `configs/chips/` itself.
//!
//! `BUILTIN_CHIP_NAMES` and `embedded_chip_yaml()` used to be two hand-written
//! lists that had to agree with each other AND with the directory. Three facts
//! about the same set, maintained in three places: add a chip and you must
//! remember both lists, or the chip exists on disk, resolves by path, and is
//! rejected by bare name with a message listing every chip except the new one.
//!
//! Generating them removes the question. The directory IS the registry, so the
//! lists cannot drift from it — there is nothing left to keep in step.
//!
//! ## The exclusion is deliberate, and it is not a heuristic
//!
//! `configs/chips/` holds 29 YAMLs and only 26 are shippable. The other three
//! are `ci-fixture-*`: synthetic descriptors that exist to drive gate tests
//! (a Cortex-M3 on UART1, a bare RISC-V, an unknown-arch case). Scanning the
//! directory naively would advertise `ci-fixture-riscv` to users as a chip they
//! can build for, which is worse than the drift this replaces.
//!
//! So the prefix is excluded explicitly, and the count is asserted below: if
//! the shippable total changes, the build says so rather than quietly shipping
//! a fixture or dropping a real part.

use std::collections::BTreeSet;
use std::path::Path;

/// Descriptors that exist only to drive tests. Never advertised as built-ins.
const FIXTURE_PREFIX: &str = "ci-fixture-";

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let chips_dir = Path::new(&manifest).join("../../configs/chips");
    let chips_dir = chips_dir
        .canonicalize()
        .unwrap_or_else(|e| panic!("configs/chips not found at {}: {e}", chips_dir.display()));

    // Re-run when a chip is added, removed or renamed. Without this the
    // generated registry is whatever the last build saw, which would reintroduce
    // exactly the staleness this replaces.
    println!("cargo:rerun-if-changed={}", chips_dir.display());

    let mut names: BTreeSet<String> = BTreeSet::new();
    for entry in std::fs::read_dir(&chips_dir).expect("read configs/chips") {
        let path = entry.expect("dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("yaml") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("chip file stem")
            .to_string();
        if stem.starts_with(FIXTURE_PREFIX) {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());
        names.insert(stem);
    }

    assert!(
        !names.is_empty(),
        "no shippable chip descriptors found in {} — refusing to generate an \
         empty built-in registry, which would make every bare chip name fail to \
         resolve while the build stayed green",
        chips_dir.display()
    );

    let mut out = String::new();
    out.push_str("// @generated by crates/config/build.rs from configs/chips/. Do not edit.\n\n");
    out.push_str("/// Chip names the CLI carries. Generated from `configs/chips/`.\n");
    out.push_str("pub const BUILTIN_CHIP_NAMES: &[&str] = &[\n");
    for name in &names {
        out.push_str(&format!("    {name:?},\n"));
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// The YAML for a built-in chip. `include_str!` bundles them so a released\n\
         /// binary carries them and wasm builds (no `std::fs`) resolve them too.\n\
         pub fn embedded_chip_yaml(name: &str) -> Option<&'static str> {\n    Some(match name {\n",
    );
    for name in &names {
        let path = chips_dir.join(format!("{name}.yaml"));
        out.push_str(&format!(
            "        {name:?} => include_str!({:?}),\n",
            path.to_str().expect("utf8 chip path")
        ));
    }
    out.push_str("        _ => return None,\n    })\n}\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("builtin_chips.rs");
    std::fs::write(&dest, out).expect("write builtin_chips.rs");
}
