name: x86
description: 'Hardware target. Family: x86 Generic, Architecture: Other'
family: x86 Generic
code_example: "/* Simple x86 Hello World */\n#include <stdio.h>\nint main(void) {\n\
  \    printf(\"LabWired x86 Boot Successful!\\n\");\n    while(1);\n    return 0;\n\
  }"
pass_rate: 100
verified: true
system: systems/onboarding/x86.yaml
sample_trace: traces/x86_generic.txt
