# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: x86_64-kvm
description: 'Hardware target. Family: x86 Generic, Architecture: Other'
family: x86 Generic
code_example: "/* Simple x86 Hello World */\n#include <stdio.h>\nint main(void) {\n\
  \    printf(\"LabWired x86 Boot Successful!\\n\");\n    while(1);\n    return 0;\n\
  }"
pass_rate: 0
verified: false
system: systems/onboarding/x86_64-kvm.yaml
sample_trace: traces/x86_generic.txt
