MEMORY
{
  FLASH : ORIGIN = 0x42000000, LENGTH = 4M
  RAM   : ORIGIN = 0x3FC80000, LENGTH = 400K
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
