// @generated by scripts/gen_esp_systimer_regs.py from tests/fixtures/svd/esp32s3.svd
// DO NOT EDIT BY HAND — re-run: python3 scripts/gen_esp_systimer_regs.py
//
// ESP32-C3 SYSTIMER is the same IP block (identical freerunning offsets);
// S3 SVD is the superset (includes REAL_TARGET*).

//! SYSTIMER register offsets derived from the checked-in SVD.

pub const CONF: u64 = 0x0;
pub const UNIT0_OP: u64 = 0x4;
pub const UNIT1_OP: u64 = 0x8;
pub const UNIT0_LOAD_HI: u64 = 0xC;
pub const UNIT0_LOAD_LO: u64 = 0x10;
pub const UNIT1_LOAD_HI: u64 = 0x14;
pub const UNIT1_LOAD_LO: u64 = 0x18;
pub const TARGET0_HI: u64 = 0x1C;
pub const TARGET0_LO: u64 = 0x20;
pub const TARGET1_HI: u64 = 0x24;
pub const TARGET1_LO: u64 = 0x28;
pub const TARGET2_HI: u64 = 0x2C;
pub const TARGET2_LO: u64 = 0x30;
pub const TARGET0_CONF: u64 = 0x34;
pub const TARGET1_CONF: u64 = 0x38;
pub const TARGET2_CONF: u64 = 0x3C;
pub const UNIT0_VALUE_HI: u64 = 0x40;
pub const UNIT0_VALUE_LO: u64 = 0x44;
pub const UNIT1_VALUE_HI: u64 = 0x48;
pub const UNIT1_VALUE_LO: u64 = 0x4C;
pub const COMP0_LOAD: u64 = 0x50;
pub const COMP1_LOAD: u64 = 0x54;
pub const COMP2_LOAD: u64 = 0x58;
pub const UNIT0_LOAD: u64 = 0x5C;
pub const UNIT1_LOAD: u64 = 0x60;
pub const INT_ENA: u64 = 0x64;
pub const INT_RAW: u64 = 0x68;
pub const INT_CLR: u64 = 0x6C;
pub const INT_ST: u64 = 0x70;
pub const REAL_TARGET0_LO: u64 = 0x74;
pub const REAL_TARGET0_HI: u64 = 0x78;
pub const REAL_TARGET1_LO: u64 = 0x7C;
pub const REAL_TARGET1_HI: u64 = 0x80;
pub const REAL_TARGET2_LO: u64 = 0x84;
pub const REAL_TARGET2_HI: u64 = 0x88;
pub const DATE: u64 = 0xFC;

/// Freerunning snapshot path (esp_timer / Arduino millis).
/// Derived from the named SVD offsets above.
pub const FREERUNNING_POLL: &[u64] = &[
    UNIT0_OP,
    UNIT1_OP,
    UNIT0_VALUE_HI,
    UNIT0_VALUE_LO,
    UNIT1_VALUE_HI,
    UNIT1_VALUE_LO,
];
