#!/usr/bin/env python3
"""Arduino sketch × LabWired board matrix.

For every board in boards.yaml and every sketch (L0/L1/L2):
  1. Compile with PlatformIO (framework=arduino) — unless --sim-only / cache hit
  2. Run with `labwired test` against the board system manifest
  3. Record pass/fail with stage and UART (and optional L2 GPIO edges)

Shared engine: validation/matrix_lib/  (see docs/engineering/test_harness.md)

Usage (from repo core/):
  python3 validation/arduino-matrix/run_matrix.py
  python3 validation/arduino-matrix/run_matrix.py --boards stm32f103,esp32
  python3 validation/arduino-matrix/run_matrix.py --sim-only --sketches L2_blink_serial
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import textwrap
import time
from pathlib import Path

# Allow `import matrix_lib` from sibling validation/
_VALIDATION = Path(__file__).resolve().parent.parent
if str(_VALIDATION) not in sys.path:
    sys.path.insert(0, str(_VALIDATION))

from matrix_lib import (  # noqa: E402
    compile_fingerprint,
    elf_cache_hit,
    find_labwired,
    render_scoreboard,
    run_labwired,
    write_fingerprint,
    write_test_script,
)
from matrix_lib.invoke import CORE_ROOT  # noqa: E402

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required — pip install pyyaml", file=sys.stderr)
    sys.exit(2)

MATRIX_DIR = Path(__file__).resolve().parent
DEFAULT_OUT = MATRIX_DIR / "out"


def load_config() -> dict:
    with open(MATRIX_DIR / "boards.yaml", encoding="utf-8") as f:
        return yaml.safe_load(f)


def write_pio_project(work: Path, board: dict, sketch_src: Path) -> Path:
    """Materialize a one-shot PlatformIO project for board × sketch."""
    work.mkdir(parents=True, exist_ok=True)
    pio = board["pio"]
    boards_dir = MATRIX_DIR / "pio-boards"
    boards_dir_line = ""
    if (boards_dir / f"{pio['board']}.json").is_file():
        boards_dir_line = f"boards_dir = {boards_dir}\n"
    ini = textwrap.dedent(
        f"""\
        ; Generated by run_matrix.py — do not hand-edit
        [platformio]
        {boards_dir_line}[env:matrix]
        platform = {pio['platform']}
        board = {pio['board']}
        framework = {pio['framework']}
        monitor_speed = 115200
        build_flags =
            -DCORE_DEBUG_LEVEL=0
        """
    )
    (work / "platformio.ini").write_text(ini, encoding="utf-8")
    src_dir = work / "src"
    if src_dir.exists():
        shutil.rmtree(src_dir)
    shutil.copytree(sketch_src, src_dir)
    return work


def compile_sketch(work: Path, log_path: Path, timeout: int) -> tuple[bool, str, Path | None]:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    # Always resolve: relative work + cwd=work + `-d relative` makes pio look for
    # work/work and fail with "Path does not exist" (CI roast round-2).
    work = work.resolve()
    log_path = log_path.resolve()
    # cwd is the project; do not pass a relative -d (would be re-resolved from cwd).
    cmd = ["pio", "run", "-e", "matrix"]
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(work),
        )
    except subprocess.TimeoutExpired as e:
        log_path.write_text((e.stdout or "") + "\nTIMEOUT\n" + (e.stderr or ""), encoding="utf-8")
        return False, "compile_timeout", None
    except FileNotFoundError:
        log_path.write_text("pio not found on PATH\n", encoding="utf-8")
        return False, "pio_missing", None

    log_path.write_text(proc.stdout + "\n--- stderr ---\n" + proc.stderr, encoding="utf-8")
    if proc.returncode != 0:
        blob = (proc.stdout + proc.stderr).lower()
        if (
            "unknown board" in blob
            or "unknown platform" in blob
            or "could not find the package" in blob
        ):
            return False, "toolchain_missing", None
        return False, "compile_fail", None

    build_dir = work / ".pio" / "build" / "matrix"
    elf = build_dir / "firmware.elf"
    if not elf.is_file():
        candidates = list(build_dir.glob("*.elf")) if build_dir.is_dir() else []
        if not candidates:
            return False, "elf_missing", None
        elf = candidates[0]
    return True, "ok", elf


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--boards", help="Comma-separated board ids (default: all)")
    ap.add_argument("--sketches", help="Comma-separated sketch ids (default: all)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--labwired", help="Path to labwired CLI")
    ap.add_argument("--compile-timeout", type=int, default=600)
    ap.add_argument("--run-timeout", type=int, default=300)
    ap.add_argument("--keep-work", action="store_true", help="Keep PIO work dirs")
    ap.add_argument(
        "--sim-only",
        action="store_true",
        help="Skip compile; require out/<board>/<sketch>/firmware.elf",
    )
    ap.add_argument(
        "--force-compile",
        action="store_true",
        help="Ignore ELF content-hash cache and recompile",
    )
    args = ap.parse_args()

    cfg = load_config()
    all_boards = cfg["boards"]
    all_sketches = cfg["sketches"]
    boards = all_boards
    sketches = all_sketches
    if args.boards:
        want = set(args.boards.split(","))
        boards = [b for b in boards if b["id"] in want]
    if args.sketches:
        want = set(args.sketches.split(","))
        sketches = [s for s in sketches if s["id"] in want]
    is_full_matrix = len(boards) == len(all_boards) and len(sketches) == len(all_sketches)

    labwired = find_labwired(args.labwired)
    # Absolute out dir so PIO work paths never depend on caller cwd.
    out: Path = args.out.expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    work_root = out / "_pio_work"
    work_root.mkdir(parents=True, exist_ok=True)

    print(f"labwired: {labwired}")
    print(f"boards:   {', '.join(b['id'] for b in boards)}")
    print(f"sketches: {', '.join(s['id'] for s in sketches)}")
    print(f"out:      {out}")
    if args.sim_only:
        print("mode:     sim-only (no compile)")
    print()

    rows: list[dict] = []
    t0 = time.time()

    for board in boards:
        bid = board["id"]
        system = MATRIX_DIR / board["system"]
        if not system.is_file():
            for sketch in sketches:
                rows.append(
                    {
                        "board": bid,
                        "sketch": sketch["id"],
                        "status": "sim_error",
                        "detail": f"missing system manifest: {system}",
                    }
                )
            continue

        if board.get("skip_reason"):
            for sketch in sketches:
                print(f"==> {bid} × {sketch['id']}: skip ({board['skip_reason']})", flush=True)
                rows.append(
                    {
                        "board": bid,
                        "sketch": sketch["id"],
                        "status": "toolchain_missing",
                        "detail": board["skip_reason"],
                    }
                )
            continue

        for sketch in sketches:
            sid = sketch["id"]
            skip_sk = board.get("sketches_skip") or []
            if sid in skip_sk:
                reason = (board.get("sketches_skip_reason") or {}).get(sid) or board.get(
                    "l3_skip_reason", "board sketches_skip"
                )
                print(f"==> {bid} × {sid}: skip ({reason})", flush=True)
                rows.append(
                    {
                        "board": bid,
                        "sketch": sid,
                        "status": "skipped",
                        "detail": reason,
                    }
                )
                continue
            cell_out = out / bid / sid
            cell_out.mkdir(parents=True, exist_ok=True)
            print(f"==> {bid} × {sid}", flush=True)

            sketch_src = MATRIX_DIR / sketch["dir"] / "src"
            pio = board["pio"]
            digest = compile_fingerprint(
                board_id=bid,
                sketch_id=sid,
                sketch_src=sketch_src,
                pio_platform=pio["platform"],
                pio_board=pio["board"],
                pio_framework=pio["framework"],
                extra={"max_steps": board.get("max_steps"), "led_watch": board.get("led_watch")},
            )

            cached_elf = cell_out / "firmware.elf"
            used_cache = False
            if args.sim_only:
                if not cached_elf.is_file():
                    print("    compile: missing firmware.elf (--sim-only)", flush=True)
                    rows.append(
                        {
                            "board": bid,
                            "sketch": sid,
                            "status": "elf_missing",
                            "detail": "sim-only requires existing firmware.elf",
                        }
                    )
                    continue
                print("    compile: skipped (--sim-only)", flush=True)
            elif not args.force_compile and elf_cache_hit(cell_out, digest):
                used_cache = True
                print(f"    compile: cache hit ({cached_elf.name})", flush=True)
            else:
                work = work_root / f"{bid}__{sid}"
                write_pio_project(work, board, sketch_src)
                if "wba" in bid.lower() or "wba" in str(board.get("chip", "")).lower():
                    patch = MATRIX_DIR / "scripts" / "patch_stm32duino_wba_series.py"
                    if patch.is_file():
                        subprocess.run(
                            [sys.executable, str(patch)],
                            check=False,
                            capture_output=True,
                            text=True,
                        )
                ok, stage, elf = compile_sketch(
                    work, cell_out / "compile.log", args.compile_timeout
                )
                if not ok or elf is None:
                    print(f"    compile: {stage}", flush=True)
                    rows.append({"board": bid, "sketch": sid, "status": stage, "detail": stage})
                    continue
                print(f"    compile: ok ({elf.name})", flush=True)
                shutil.copy2(elf, cached_elf)
                pt_src = elf.parent / "partitions.bin"
                if pt_src.is_file():
                    shutil.copy2(pt_src, cell_out / "partitions.bin")
                write_fingerprint(cell_out, digest)
                if not args.keep_work:
                    try:
                        shutil.rmtree(work)
                    except OSError:
                        pass

            # L2 optional GPIO / RMT honesty (boards.yaml)
            watch: list[str] = []
            min_edges: int | None = None
            min_rmt: int | None = None
            if sid.startswith("L2"):
                if board.get("led_watch"):
                    watch = [str(board["led_watch"])]
                    min_edges = int(board.get("led_min_edges", 2))
                if board.get("min_rmt_tx") is not None:
                    min_rmt = int(board["min_rmt_tx"])

            script = cell_out / "test.yaml"
            write_test_script(
                script,
                cached_elf,
                system,
                sketch["marker"],
                int(board.get("max_steps", 5_000_000)),
            )
            status, detail = run_labwired(
                labwired,
                script,
                cell_out / "run",
                args.run_timeout,
                watch_gpio=watch or None,
                min_logic_edges=min_edges,
                min_rmt_tx=min_rmt,
            )
            if used_cache:
                detail = dict(detail) if isinstance(detail, dict) else {"detail": detail}
                detail["compile"] = "cache_hit"
            print(f"    run: {status}", flush=True)
            rows.append({"board": bid, "sketch": sid, "status": status, "detail": detail})

    elapsed = time.time() - t0
    results = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "elapsed_s": round(elapsed, 1),
        "labwired": str(labwired),
        "sim_only": bool(args.sim_only),
        "rows": rows,
    }
    (out / "results.json").write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    scoreboard = render_scoreboard(
        rows,
        title="Arduino × LabWired board matrix",
        generator="validation/arduino-matrix/run_matrix.py",
        board_ids=[b["id"] for b in boards],
        cell_ids=[s["id"] for s in sketches],
    )
    (out / "scoreboard.md").write_text(scoreboard, encoding="utf-8")
    docs_out = CORE_ROOT / "docs" / "coverage" / "arduino-scoreboard.md"
    if is_full_matrix:
        docs_out.parent.mkdir(parents=True, exist_ok=True)
        docs_out.write_text(scoreboard, encoding="utf-8")
        pub_note = f"Published:  {docs_out}"
    else:
        pub_note = (
            f"Docs scoreboard unchanged "
            f"(partial run; not full {len(all_boards)}×{len(all_sketches)})"
        )

    passed = sum(1 for r in rows if r["status"] in ("pass", "skipped"))
    failed = sum(1 for r in rows if r["status"] not in ("pass", "skipped"))
    print()
    print(f"Done in {elapsed:.0f}s — {passed}/{len(rows)} pass/skip ({failed} fail)")
    print(f"Scoreboard: {out / 'scoreboard.md'}")
    print(pub_note)
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
