# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: ezr32wg330
chip: ../../chips/onboarding/ezr32wg330.yaml
