# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: murax_vexriscv_verilated_uart
chip: ../../chips/onboarding/murax_vexriscv_verilated_uart.yaml
