# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: quark_c1000-cc2520
chip: ../../chips/onboarding/quark_c1000-cc2520.yaml
