# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: "stm32f401cdu6-blackpill"
chip: "../../chips/onboarding/stm32f401cdu6-blackpill.yaml"
external_devices: []
board_io:
  - id: "led_pc13"
    kind: "led"
    peripheral: "gpioc"
    pin: 13
    signal: "output"
    active_high: false
  - id: "button_user_pa0"
    kind: "button"
    peripheral: "gpioa"
    pin: 0
    signal: "input"
    active_high: true
