# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: ut32m0r500
chip: ../../chips/onboarding/ut32m0r500.yaml
