peripheral: UARTE0
version: 0.1.0
registers:
- id: TASKS_STARTRX
  address_offset: 0
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields: []
  side_effects: null
- id: TASKS_STOPRX
  address_offset: 4
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields: []
  side_effects: null
- id: TASKS_STARTTX
  address_offset: 8
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields: []
  side_effects: null
- id: TASKS_STOPTX
  address_offset: 12
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields: []
  side_effects: null
- id: TASKS_FLUSHRX
  address_offset: 44
  size: 32
  access: WRITE_ONLY
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_CTS
  address_offset: 256
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_NCTS
  address_offset: 260
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_RXDRDY
  address_offset: 264
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_ENDRX
  address_offset: 272
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_TXDRDY
  address_offset: 284
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_ENDTX
  address_offset: 288
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_ERROR
  address_offset: 292
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_RXTO
  address_offset: 324
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_RXSTARTED
  address_offset: 332
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_TXSTARTED
  address_offset: 336
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: EVENTS_TXSTOPPED
  address_offset: 344
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields: []
  side_effects: null
- id: SHORTS
  address_offset: 512
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: ENDRX_STARTRX
    bit_range:
    - 5
    - 5
    description: Shortcut between ENDRX event and STARTRX task
  - name: ENDRX_STOPRX
    bit_range:
    - 6
    - 6
    description: Shortcut between ENDRX event and STOPRX task
  side_effects: null
- id: INTEN
  address_offset: 768
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CTS
    bit_range:
    - 0
    - 0
    description: Enable or disable interrupt for CTS event
  - name: NCTS
    bit_range:
    - 1
    - 1
    description: Enable or disable interrupt for NCTS event
  - name: RXDRDY
    bit_range:
    - 2
    - 2
    description: Enable or disable interrupt for RXDRDY event
  - name: ENDRX
    bit_range:
    - 4
    - 4
    description: Enable or disable interrupt for ENDRX event
  - name: TXDRDY
    bit_range:
    - 7
    - 7
    description: Enable or disable interrupt for TXDRDY event
  - name: ENDTX
    bit_range:
    - 8
    - 8
    description: Enable or disable interrupt for ENDTX event
  - name: ERROR
    bit_range:
    - 9
    - 9
    description: Enable or disable interrupt for ERROR event
  - name: RXTO
    bit_range:
    - 17
    - 17
    description: Enable or disable interrupt for RXTO event
  - name: RXSTARTED
    bit_range:
    - 19
    - 19
    description: Enable or disable interrupt for RXSTARTED event
  - name: TXSTARTED
    bit_range:
    - 20
    - 20
    description: Enable or disable interrupt for TXSTARTED event
  - name: TXSTOPPED
    bit_range:
    - 22
    - 22
    description: Enable or disable interrupt for TXSTOPPED event
  side_effects: null
- id: INTENSET
  address_offset: 772
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CTS
    bit_range:
    - 0
    - 0
    description: Write '1' to Enable interrupt for CTS event
  - name: NCTS
    bit_range:
    - 1
    - 1
    description: Write '1' to Enable interrupt for NCTS event
  - name: RXDRDY
    bit_range:
    - 2
    - 2
    description: Write '1' to Enable interrupt for RXDRDY event
  - name: ENDRX
    bit_range:
    - 4
    - 4
    description: Write '1' to Enable interrupt for ENDRX event
  - name: TXDRDY
    bit_range:
    - 7
    - 7
    description: Write '1' to Enable interrupt for TXDRDY event
  - name: ENDTX
    bit_range:
    - 8
    - 8
    description: Write '1' to Enable interrupt for ENDTX event
  - name: ERROR
    bit_range:
    - 9
    - 9
    description: Write '1' to Enable interrupt for ERROR event
  - name: RXTO
    bit_range:
    - 17
    - 17
    description: Write '1' to Enable interrupt for RXTO event
  - name: RXSTARTED
    bit_range:
    - 19
    - 19
    description: Write '1' to Enable interrupt for RXSTARTED event
  - name: TXSTARTED
    bit_range:
    - 20
    - 20
    description: Write '1' to Enable interrupt for TXSTARTED event
  - name: TXSTOPPED
    bit_range:
    - 22
    - 22
    description: Write '1' to Enable interrupt for TXSTOPPED event
  side_effects: null
- id: INTENCLR
  address_offset: 776
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: CTS
    bit_range:
    - 0
    - 0
    description: Write '1' to Disable interrupt for CTS event
  - name: NCTS
    bit_range:
    - 1
    - 1
    description: Write '1' to Disable interrupt for NCTS event
  - name: RXDRDY
    bit_range:
    - 2
    - 2
    description: Write '1' to Disable interrupt for RXDRDY event
  - name: ENDRX
    bit_range:
    - 4
    - 4
    description: Write '1' to Disable interrupt for ENDRX event
  - name: TXDRDY
    bit_range:
    - 7
    - 7
    description: Write '1' to Disable interrupt for TXDRDY event
  - name: ENDTX
    bit_range:
    - 8
    - 8
    description: Write '1' to Disable interrupt for ENDTX event
  - name: ERROR
    bit_range:
    - 9
    - 9
    description: Write '1' to Disable interrupt for ERROR event
  - name: RXTO
    bit_range:
    - 17
    - 17
    description: Write '1' to Disable interrupt for RXTO event
  - name: RXSTARTED
    bit_range:
    - 19
    - 19
    description: Write '1' to Disable interrupt for RXSTARTED event
  - name: TXSTARTED
    bit_range:
    - 20
    - 20
    description: Write '1' to Disable interrupt for TXSTARTED event
  - name: TXSTOPPED
    bit_range:
    - 22
    - 22
    description: Write '1' to Disable interrupt for TXSTOPPED event
  side_effects: null
- id: ERRORSRC
  address_offset: 1152
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: OVERRUN
    bit_range:
    - 0
    - 0
    description: Overrun error
  - name: PARITY
    bit_range:
    - 1
    - 1
    description: Parity error
  - name: FRAMING
    bit_range:
    - 2
    - 2
    description: Framing error occurred
  - name: BREAK
    bit_range:
    - 3
    - 3
    description: Break condition
  side_effects:
    read_action: null
    write_action: write_one_to_clear
    on_read: null
    on_write: null
- id: ENABLE
  address_offset: 1280
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: ENABLE
    bit_range:
    - 3
    - 0
    description: Enable or disable UARTE
  side_effects: null
- id: PSEL_RTS
  address_offset: 1288
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: PIN
    bit_range:
    - 4
    - 0
    description: Pin number
  - name: CONNECT
    bit_range:
    - 31
    - 31
    description: Connection
  side_effects: null
- id: PSEL_TXD
  address_offset: 1292
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: PIN
    bit_range:
    - 4
    - 0
    description: Pin number
  - name: CONNECT
    bit_range:
    - 31
    - 31
    description: Connection
  side_effects: null
- id: PSEL_CTS
  address_offset: 1296
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: PIN
    bit_range:
    - 4
    - 0
    description: Pin number
  - name: CONNECT
    bit_range:
    - 31
    - 31
    description: Connection
  side_effects: null
- id: PSEL_RXD
  address_offset: 1300
  size: 32
  access: READ_WRITE
  reset_value: 4294967295
  fields:
  - name: PIN
    bit_range:
    - 4
    - 0
    description: Pin number
  - name: CONNECT
    bit_range:
    - 31
    - 31
    description: Connection
  side_effects: null
- id: BAUDRATE
  address_offset: 1316
  size: 32
  access: READ_WRITE
  reset_value: 67108864
  fields:
  - name: BAUDRATE
    bit_range:
    - 31
    - 0
    description: Baud rate
  side_effects: null
- id: RXD_PTR
  address_offset: 1332
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PTR
    bit_range:
    - 31
    - 0
    description: Data pointer
  side_effects: null
- id: RXD_MAXCNT
  address_offset: 1336
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MAXCNT
    bit_range:
    - 7
    - 0
    description: Maximum number of bytes in receive buffer
  side_effects: null
- id: RXD_AMOUNT
  address_offset: 1340
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: AMOUNT
    bit_range:
    - 7
    - 0
    description: Number of bytes transferred in the last transaction
  side_effects: null
- id: TXD_PTR
  address_offset: 1348
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: PTR
    bit_range:
    - 31
    - 0
    description: Data pointer
  side_effects: null
- id: TXD_MAXCNT
  address_offset: 1352
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: MAXCNT
    bit_range:
    - 7
    - 0
    description: Maximum number of bytes in transmit buffer
  side_effects: null
- id: TXD_AMOUNT
  address_offset: 1356
  size: 32
  access: READ_ONLY
  reset_value: 0
  fields:
  - name: AMOUNT
    bit_range:
    - 7
    - 0
    description: Number of bytes transferred in the last transaction
  side_effects: null
- id: CONFIG
  address_offset: 1388
  size: 32
  access: READ_WRITE
  reset_value: 0
  fields:
  - name: HWFC
    bit_range:
    - 0
    - 0
    description: Hardware flow control
  - name: PARITY
    bit_range:
    - 3
    - 1
    description: Parity
  side_effects: null
interrupts:
  UARTE0_UART0: 2
timing: null
