// LabWired - Firmware Simulation Platform
// Copyright (C) 2026 Andrii Shylenko
//
// This software is released under the MIT License.
// See the LICENSE file in the project root for full license information.

//! Generates the fixture's `memory.x` from the environment.
//!
//! Same contract as `crates/firmware-perf-spin/build.rs`: the perf gate passes
//! the origins it read out of the chip descriptor, so a RISC-V part on a new
//! memory map is covered by adding it to FIXTURES in
//! `scripts/perf/board_perf.py` rather than by editing a linker script here.

use std::env;
use std::fs;
use std::path::PathBuf;

// The ESP32-C3 map: flash (IROM) @ 0x42000000, SRAM @ 0x3FC80000.
const DEFAULT_FLASH_ORIGIN: &str = "0x42000000";
const DEFAULT_RAM_ORIGIN: &str = "0x3FC80000";

const FLASH_LENGTH: &str = "64K";
const RAM_LENGTH: &str = "32K";

fn main() {
    let flash =
        env::var("LABWIRED_PERF_FLASH_ORIGIN").unwrap_or_else(|_| DEFAULT_FLASH_ORIGIN.to_string());
    let ram =
        env::var("LABWIRED_PERF_RAM_ORIGIN").unwrap_or_else(|_| DEFAULT_RAM_ORIGIN.to_string());

    // riscv-rt drives placement through REGION_ALIAS rather than bare FLASH /
    // RAM names, so the aliases are part of the generated script.
    let memory_x = format!(
        "/* Generated by build.rs — edit the origins via \
         LABWIRED_PERF_FLASH_ORIGIN / LABWIRED_PERF_RAM_ORIGIN. */\n\
         MEMORY\n\
         {{\n  \
         FLASH : ORIGIN = {flash}, LENGTH = {FLASH_LENGTH}\n  \
         RAM : ORIGIN = {ram}, LENGTH = {RAM_LENGTH}\n\
         }}\n\n\
         REGION_ALIAS(\"REGION_TEXT\", FLASH);\n\
         REGION_ALIAS(\"REGION_RODATA\", FLASH);\n\
         REGION_ALIAS(\"REGION_DATA\", RAM);\n\
         REGION_ALIAS(\"REGION_BSS\", RAM);\n\
         REGION_ALIAS(\"REGION_HEAP\", RAM);\n\
         REGION_ALIAS(\"REGION_STACK\", RAM);\n"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("memory.x"), memory_x).unwrap();
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rustc-link-arg=-Tmemory.x");
    println!("cargo:rustc-link-arg=-Tlink.x");
    println!("cargo:rerun-if-env-changed=LABWIRED_PERF_FLASH_ORIGIN");
    println!("cargo:rerun-if-env-changed=LABWIRED_PERF_RAM_ORIGIN");
}
