# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: a20
arch: arm
flash:
  base: 4294901760
  size: 65536B
ram:
  base: 536870912
  size: 262144B
peripherals:
- id: uart0
  type: ns16550
  bus: sysbus
  base_address: 29523968
- id: uart1
  type: ns16550
  bus: sysbus
  base_address: 29524992
- id: uart2
  type: ns16550
  bus: sysbus
  base_address: 29526016
- id: uart3
  type: ns16550
  bus: sysbus
  base_address: 29527040
- id: uart4
  type: ns16550
  bus: sysbus
  base_address: 29528064
- id: uart5
  type: ns16550
  bus: sysbus
  base_address: 29529088
- id: uart6
  type: ns16550
  bus: sysbus
  base_address: 29530112
- id: uart7
  type: ns16550
  bus: sysbus
  base_address: 29531136
- id: usbEhci1
  type: ehcihostcontroller
  bus: sysbus
  base_address: 29442048
- id: usbHub
  type: usbhub
  bus: usbEhci1
  base_address: 1
- id: usbEhci2
  type: ehcihostcontroller
  bus: sysbus
  base_address: 29474816
- id: timer
  type: arm_generictimer
  bus: cpu
  base_address: 15
- id: sunxiMmc0
  type: sunximmc
  bus: sysbus
  base_address: 29421568
- id: sunxiMmc1
  type: sunximmc
  bus: sysbus
  base_address: 29425664
- id: sunxiMmc3
  type: sunximmc
  bus: sysbus
  base_address: 29433856
- id: sunxiHstimer
  type: sunxihighspeedtimer
  bus: sysbus
  base_address: 29753344
- id: sunxiTimer
  type: sunxitimer
  bus: sysbus
  base_address: 29494272
