# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: acrn_x86_64
arch: arm
flash:
  base: 0
  size: 16711680B
ram:
  base: 16777216
  size: 536870912B
peripherals:
- id: uart
  type: ns16550
  bus: sysbus
  base_address: 3758097400
- id: hpet
  type: hpet
  bus: sysbus
  base_address: 4275044352
