# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: brd4186c
arch: arm
flash:
  base: 134217728
  size: 1564672B
ram:
  base: 536870912
  size: 262144B
peripherals:
- id: led0
  type: led
  bus: gpioPort
  base_address: 66
- id: led1
  type: led
  bus: gpioPort
  base_address: 67
- id: button0
  type: button
  bus: gpioPort
  base_address: 64
- id: button1
  type: button
  bus: gpioPort
  base_address: 65
- id: DCDC_IF
  type: pythonperipheral
  bus: sysbus
  base_address: 1342783528
