# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: cortex-a53-gicv3
arch: arm
flash:
  base: 134217728
  size: 134217728B
ram:
  base: 1073741824
  size: 2147483648B
peripherals:
- id: timer
  type: arm_generictimer
  bus: cpu
  base_address: 15
- id: uart0
  type: pl011
  bus: sysbus
  base_address: 150994944
- id: rtc
  type: pl031
  bus: sysbus
  base_address: 151060480
