# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: cortex-a9
arch: arm
flash:
  base: 2147483648
  size: 134217728B
ram:
  base: 536870912
  size: 64KB
peripherals:
- id: scu
  type: armsnoopcontrolunit
  bus: sysbus
  base_address: 2919235584
