# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: efm32pg12
arch: arm
flash:
  base: 134217728
  size: 1048576B
ram:
  base: 536870912
  size: 262144B
peripherals:
- id: usart0
  type: efm32_uart
  bus: sysbus
  base_address: 1073807360
- id: usart1
  type: efm32_uart
  bus: sysbus
  base_address: 1073808384
- id: usart2
  type: efm32_uart
  bus: sysbus
  base_address: 1073809408
- id: usart3
  type: efm32_uart
  bus: sysbus
  base_address: 1073810432
- id: leUart0
  type: leuart
  bus: sysbus
  base_address: 1074044928
- id: bitband
  type: bitbanding
  bus: sysbus
  base_address: 1107296256
- id: cmuStatusOscillator
  type: pythonperipheral
  bus: sysbus
  base_address: 1074561068
- id: vcmpStatus
  type: pythonperipheral
  bus: sysbus
  base_address: 1073741832
