# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: kendryte_k210
arch: arm
flash:
  base: 2147483648
  size: 33554432B
ram:
  base: 0
  size: 64KB
peripherals:
- id: uart
  type: sifive_uart
  bus: sysbus
  base_address: 939524096
