# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: leon3-externals
arch: arm
flash:
  base: 0
  size: 256KB
ram:
  base: 0
  size: 64KB
peripherals:
- id: phy
  type: ethernetphysicallayer
  bus: eth
  base_address: 0
- id: led
  type: led
  bus: gpio
  base_address: 0
