# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: litex_nexys_video_vexriscv_linux
arch: arm
flash:
  base: 0
  size: 65536B
ram:
  base: 268435456
  size: 8192B
peripherals: []
