# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: litex_zephyr_vexriscv_i2s
arch: arm
flash:
  base: 1073741824
  size: 268435456B
ram:
  base: 1073741824
  size: 268435456B
peripherals: []
