name: litex_vexriscv_verilated_liteuart
arch: arm
flash:
  base: 536870912
  size: 1048576
ram:
  base: 268435456
  size: 262144B
peripherals:
- id: uart
  type: cosimulateduart
  bus: sysbus
  base_address: 3758100480
