# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: litex_vexriscv_smp
arch: arm
flash:
  base: 1073741824
  size: 134217728B
ram:
  base: 1073741824
  size: 134217728B
peripherals:
- id: uart
  type: litex_uart
  bus: sysbus
  base_address: 4026537984
