# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: max32652-evkit
arch: arm
flash:
  base: 268435456
  size: 3145728B
ram:
  base: 536870912
  size: 1048576B
peripherals:
- id: led0
  type: led
  bus: gpio2
  base_address: 25
- id: led1
  type: led
  bus: gpio2
  base_address: 26
- id: gcr
  type: max32650_gcr
  bus: sysbus
  base_address: 1073741824
- id: wdt0
  type: max32650_wdt
  bus: sysbus
  base_address: 1073754112
- id: wdt1
  type: max32650_wdt
  bus: sysbus
  base_address: 1073755136
- id: timer0
  type: max32650_timer
  bus: sysbus
  base_address: 1073807360
- id: timer1
  type: max32650_timer
  bus: sysbus
  base_address: 1073811456
- id: tpu
  type: max32650_tpu
  bus: sysbus
  base_address: 1073745920
- id: timer2
  type: max32650_timer
  bus: sysbus
  base_address: 1073815552
- id: timer3
  type: max32650_timer
  bus: sysbus
  base_address: 1073819648
- id: timer4
  type: max32650_timer
  bus: sysbus
  base_address: 1073823744
- id: timer5
  type: max32650_timer
  bus: sysbus
  base_address: 1073827840
- id: i2c0
  type: max32650_i2c
  bus: sysbus
  base_address: 1073860608
- id: i2c1
  type: max32650_i2c
  bus: sysbus
  base_address: 1073864704
- id: adc
  type: max32650_adc
  bus: sysbus
  base_address: 1073954816
- id: uart0
  type: max32650_uart
  bus: sysbus
  base_address: 1074012160
- id: uart1
  type: max32650_uart
  bus: sysbus
  base_address: 1074016256
- id: uart2
  type: max32650_uart
  bus: sysbus
  base_address: 1074020352
- id: spi0
  type: max32650_spi
  bus: sysbus
  base_address: 1074028544
- id: spi1
  type: max32650_spi
  bus: sysbus
  base_address: 1074032640
- id: spi2
  type: max32650_spi
  bus: sysbus
  base_address: 1074036736
- id: gpio0
  type: max32650_gpio
  bus: sysbus
  base_address: 1073774592
- id: gpio1
  type: max32650_gpio
  bus: sysbus
  base_address: 1073778688
- id: gpio2
  type: max32650_gpio
  bus: sysbus
  base_address: 1073782784
- id: gpio3
  type: max32650_gpio
  bus: sysbus
  base_address: 1073786880
- id: spi3
  type: max32650_spi
  bus: sysbus
  base_address: 1074520064
- id: rtc
  type: max32650_rtc
  bus: sysbus
  base_address: 1073766400
- id: pwrseq
  type: max32650_pwrseq
  bus: sysbus
  base_address: 1073768448
- id: dwt
  type: dwt
  bus: sysbus
  base_address: 3758100480
- id: bitbandPeripherals
  type: bitbanding
  bus: sysbus
  base_address: 1107296256
- id: bitbandSram
  type: bitbanding
  bus: sysbus
  base_address: 570425344
