# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: mimxrt1064_evk
arch: arm
flash:
  base: 1879048192
  size: 4194304B
ram:
  base: 2147483648
  size: 33554432B
peripherals:
- id: green_led
  type: led
  bus: gpio1
  base_address: 9
- id: wdog1
  type: pythonperipheral
  bus: sysbus
  base_address: 1074495488
- id: trng
  type: imx_trng
  bus: sysbus
  base_address: 1074577408
- id: wdog2
  type: pythonperipheral
  bus: sysbus
  base_address: 1074593792
- id: wdog3
  type: pythonperipheral
  bus: sysbus
  base_address: 1074511872
- id: iomuxc
  type: pythonperipheral
  bus: sysbus
  base_address: 1075806208
- id: analog01
  type: pythonperipheral
  bus: sysbus
  base_address: 1074626560
- id: analog03
  type: pythonperipheral
  bus: sysbus
  base_address: 1074626612
- id: dcdc
  type: pythonperipheral
  bus: sysbus
  base_address: 1074266112
- id: gpTimer1
  type: imx_gptimer
  bus: sysbus
  base_address: 1075757056
- id: lpuart1
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075331072
- id: lpuart2
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075347456
- id: lpuart3
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075363840
- id: lpuart4
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075380224
- id: lpuart5
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075396608
- id: lpuart6
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075412992
- id: lpuart7
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075429376
- id: lpuart8
  type: nxp_lpuart
  bus: sysbus
  base_address: 1075445760
- id: gpio1
  type: imxrt_gpio
  bus: sysbus
  base_address: 1075544064
- id: gpio2
  type: imxrt_gpio
  bus: sysbus
  base_address: 1075560448
- id: gpio3
  type: imxrt_gpio
  bus: sysbus
  base_address: 1075576832
- id: gpio4
  type: imxrt_gpio
  bus: sysbus
  base_address: 1075593216
- id: gpio5
  type: imxrt_gpio
  bus: sysbus
  base_address: 1074528256
- id: gpio6
  type: imxrt_gpio
  bus: sysbus
  base_address: 1107296256
- id: gpio7
  type: imxrt_gpio
  bus: sysbus
  base_address: 1107312640
- id: gpio8
  type: imxrt_gpio
  bus: sysbus
  base_address: 1107329024
- id: gpio9
  type: imxrt_gpio
  bus: sysbus
  base_address: 1107345408
- id: gpio10
  type: imxrt_gpio
  bus: sysbus
  base_address: 1075609600
- id: enet
  type: k6xf_ethernet
  bus: sysbus
  base_address: 1076723712
- id: enet2
  type: k6xf_ethernet
  bus: sysbus
  base_address: 1076707328
- id: flex_spi2
  type: imxrt_flexspi
  bus: sysbus
  base_address: 1076510720
- id: adc1
  type: imxrt_adc
  bus: sysbus
  base_address: 1074544640
- id: adc2
  type: imxrt_adc
  bus: sysbus
  base_address: 1074561024
- id: pwm1
  type: imxrt_pwm
  bus: sysbus
  base_address: 1077788672
- id: pwm2
  type: imxrt_pwm
  bus: sysbus
  base_address: 1077805056
- id: pwm3
  type: imxrt_pwm
  bus: sysbus
  base_address: 1077821440
- id: pwm4
  type: imxrt_pwm
  bus: sysbus
  base_address: 1077837824
