# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: mpfs-icicle-kit
arch: arm
flash:
  base: 16777216
  size: 8192B
ram:
  base: 134217728
  size: 33554432B
peripherals:
- id: led0
  type: led
  bus: gpio2
  base_address: 16
- id: led1
  type: led
  bus: gpio2
  base_address: 17
- id: led2
  type: led
  bus: gpio2
  base_address: 18
- id: led3
  type: led
  bus: gpio2
  base_address: 19
- id: button1
  type: button
  bus: gpio2
  base_address: 30
- id: button2
  type: button
  bus: gpio2
  base_address: 31
- id: button3
  type: button
  bus: gpio2
  base_address: 28
- id: pac1934
  type: pac1934
  bus: i2c1
  base_address: 65536
- id: qspi
  type: mpfs_qspi
  bus: sysbus
  base_address: 553648128
- id: sysServices
  type: mpfs_systemservices
  bus: sysbus
  base_address: 922877952
- id: syscontroller_qspi
  type: mpfs_qspi
  bus: sysbus
  base_address: 922878208
- id: pdma
  type: mpfs_pdma
  bus: sysbus
  base_address: 50331648
- id: mmuart0
  type: ns16550
  bus: sysbus
  base_address: 536870912
- id: mmuart1
  type: ns16550
  bus: sysbus
  base_address: 537919488
- id: mmuart2
  type: ns16550
  bus: sysbus
  base_address: 537927680
- id: mmuart3
  type: ns16550
  bus: sysbus
  base_address: 537935872
- id: mmuart4
  type: ns16550
  bus: sysbus
  base_address: 537944064
- id: mmc
  type: mpfs_sdcontroller
  bus: sysbus
  base_address: 536903680
- id: spi0
  type: mpfs_spi
  bus: sysbus
  base_address: 537952256
- id: spi1
  type: mpfs_spi
  bus: sysbus
  base_address: 537956352
- id: i2c0
  type: mpfs_i2c
  bus: sysbus
  base_address: 537960448
- id: i2c1
  type: mpfs_i2c
  bus: sysbus
  base_address: 537964544
- id: can0
  type: mpfs_can
  bus: sysbus
  base_address: 537968640
- id: can1
  type: mpfs_can
  bus: sysbus
  base_address: 537972736
- id: gpio0
  type: mpfs_gpio
  bus: sysbus
  base_address: 538050560
- id: gpio1
  type: mpfs_gpio
  bus: sysbus
  base_address: 538054656
- id: gpio2
  type: mpfs_gpio
  bus: sysbus
  base_address: 538058752
- id: wdog0
  type: mpfs_watchdog
  bus: sysbus
  base_address: 536875008
- id: wdog1
  type: mpfs_watchdog
  bus: sysbus
  base_address: 537923584
- id: wdog2
  type: mpfs_watchdog
  bus: sysbus
  base_address: 537931776
- id: wdog3
  type: mpfs_watchdog
  bus: sysbus
  base_address: 537939968
- id: wdog4
  type: mpfs_watchdog
  bus: sysbus
  base_address: 537948160
- id: rtc
  type: mpfs_rtc
  bus: sysbus
  base_address: 538066944
- id: mstimer
  type: mpfs_timer
  bus: sysbus
  base_address: 538071040
- id: envmCfg
  type: mpfs_envm
  bus: sysbus
  base_address: 538968064
- id: usb
  type: mpfs_usb
  bus: sysbus
  base_address: 538972160
- id: pcie0
  type: mpfs_pcie
  bus: sysbus
  base_address: 1392525312
- id: pcieRC0
  type: pcierootcomplex
  bus: pcie0
  base_address: 0
- id: pcieRC1
  type: pcierootcomplex
  bus: pcie1
  base_address: 0
- id: pcieMem
  type: pciememory
  bus: pcie1
  base_address: 1
- id: mailbox
  type: arraymemory
  bus: sysbus
  base_address: 922880000
- id: ioscb
  type: pythonperipheral
  bus: sysbus
  base_address: 923271168
- id: DDR_CTRLR
  type: mpfs_ddrmock
  bus: sysbus
  base_address: 1040191488
- id: DDR_PHY
  type: mpfs_ddrmock
  bus: sysbus
  base_address: 536899584
- id: SCB_DDR_PLL
  type: mpfs_ddrmock
  bus: sysbus
  base_address: 1040252928
- id: DDRCFG
  type: mpfs_ddrmock
  bus: sysbus
  base_address: 537395200
- id: CacheConfig_WayEnable
  type: pythonperipheral
  bus: sysbus
  base_address: 33619976
- id: TopSystemRegisters
  type: mpfs_sysreg
  bus: sysbus
  base_address: 536879104
