# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: nuvoton_npcx9m6fb_evb
arch: arm
flash:
  base: 134217728
  size: 65536B
ram:
  base: 537657344
  size: 96256B
peripherals:
- id: dwt
  type: dwt
  bus: sysbus
  base_address: 3758100480
- id: cr_uart1
  type: npcx_uart
  bus: sysbus
  base_address: 1074659328
- id: cr_uart2
  type: npcx_uart
  bus: sysbus
  base_address: 1074667520
- id: cr_uart3
  type: npcx_uart
  bus: sysbus
  base_address: 1074675712
- id: cr_uart4
  type: npcx_uart
  bus: sysbus
  base_address: 1074683904
- id: itim32_1
  type: npcx_itim
  bus: sysbus
  base_address: 1074462720
- id: itim32_2
  type: npcx_itim
  bus: sysbus
  base_address: 1074470912
- id: itim32_3
  type: npcx_itim
  bus: sysbus
  base_address: 1074479104
- id: itim32_4
  type: npcx_itim
  bus: sysbus
  base_address: 1074487296
- id: itim32_5
  type: npcx_itim
  bus: sysbus
  base_address: 1074495488
- id: itim32_6
  type: npcx_itim
  bus: sysbus
  base_address: 1074503680
- id: itim64
  type: npcx_itim
  bus: sysbus
  base_address: 1074520064
- id: image_type
  type: arraymemory
  bus: sysbus
  base_address: 1073790985
- id: twd
  type: npcx_twd
  bus: sysbus
  base_address: 1074626560
- id: mtc
  type: npcx_mtc
  bus: sysbus
  base_address: 1074491392
- id: mdma1
  type: npcx_mdma
  bus: sysbus
  base_address: 1073811712
- id: mdma2
  type: npcx_mdma
  bus: sysbus
  base_address: 1073811968
- id: mdma3
  type: npcx_mdma
  bus: sysbus
  base_address: 1073812224
- id: mdma4
  type: npcx_mdma
  bus: sysbus
  base_address: 1073812480
- id: mdma5
  type: npcx_mdma
  bus: sysbus
  base_address: 1073812736
- id: spip
  type: npcx_spip
  bus: sysbus
  base_address: 1074601984
- id: lfcg
  type: npcx_lfcg
  bus: sysbus
  base_address: 1074483456
- id: hfcg
  type: npcx_hfcg
  bus: sysbus
  base_address: 1074483200
- id: fiu
  type: npcx_fiu
  bus: sysbus
  base_address: 1073872896
- id: gpio0
  type: npcx_gpio
  bus: sysbus
  base_address: 1074270208
- id: gpio1
  type: npcx_gpio
  bus: sysbus
  base_address: 1074278400
- id: gpio2
  type: npcx_gpio
  bus: sysbus
  base_address: 1074286592
- id: gpio3
  type: npcx_gpio
  bus: sysbus
  base_address: 1074294784
- id: gpio4
  type: npcx_gpio
  bus: sysbus
  base_address: 1074302976
- id: gpio5
  type: npcx_gpio
  bus: sysbus
  base_address: 1074311168
- id: gpio6
  type: npcx_gpio
  bus: sysbus
  base_address: 1074319360
- id: gpio7
  type: npcx_gpio
  bus: sysbus
  base_address: 1074327552
- id: gpio8
  type: npcx_gpio
  bus: sysbus
  base_address: 1074335744
- id: gpio9
  type: npcx_gpio
  bus: sysbus
  base_address: 1074343936
- id: gpioa
  type: npcx_gpio
  bus: sysbus
  base_address: 1074352128
- id: gpiob
  type: npcx_gpio
  bus: sysbus
  base_address: 1074360320
- id: gpioc
  type: npcx_gpio
  bus: sysbus
  base_address: 1074368512
- id: gpiod
  type: npcx_gpio
  bus: sysbus
  base_address: 1074376704
- id: gpioe
  type: npcx_gpio
  bus: sysbus
  base_address: 1074384896
- id: gpiof
  type: npcx_gpio
  bus: sysbus
  base_address: 1074393088
- id: smbus0
  type: npcx_smbus
  bus: sysbus
  base_address: 1073778688
- id: smbus1
  type: npcx_smbus
  bus: sysbus
  base_address: 1073786880
- id: smbus2
  type: npcx_smbus
  bus: sysbus
  base_address: 1074528256
- id: smbus3
  type: npcx_smbus
  bus: sysbus
  base_address: 1074536448
- id: smbus4
  type: npcx_smbus
  bus: sysbus
  base_address: 1073774592
- id: smbus5
  type: npcx_smbus
  bus: sysbus
  base_address: 1073836032
- id: smbus6
  type: npcx_smbus
  bus: sysbus
  base_address: 1073840128
- id: smbus7
  type: npcx_smbus
  bus: sysbus
  base_address: 1073844224
- id: DEV_CTL4
  type: pythonperipheral
  bus: sysbus
  base_address: 1074540550
- id: SWRST_CTL4
  type: pythonperipheral
  bus: sysbus
  base_address: 1074540816
- id: pm1
  type: arraymemory
  bus: sysbus
  base_address: 1074565120
- id: pm2
  type: arraymemory
  bus: sysbus
  base_address: 1074573312
- id: pm3
  type: arraymemory
  bus: sysbus
  base_address: 1074581504
- id: pm4
  type: arraymemory
  bus: sysbus
  base_address: 1074589696
