# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: stm32h753
arch: arm
flash:
  base: 2147483648
  size: 268435456B
ram:
  base: 3489660928
  size: 268435456B
peripherals:
- id: flashController
  type: stm32h7_flashcontroller
  bus: sysbus
  base_address: 1375739904
- id: adc3
  type: stm32f0_adc
  bus: sysbus
  base_address: 1476550656
- id: bdma
  type: stm32ldma
  bus: sysbus
  base_address: 1476547584
- id: gpioPortK
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476536320
- id: gpioPortJ
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476535296
- id: gpioPortI
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476534272
- id: gpioPortH
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476533248
- id: gpioPortG
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476532224
- id: gpioPortF
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476531200
- id: gpioPortE
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476530176
- id: gpioPortD
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476529152
- id: gpioPortC
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476528128
- id: gpioPortB
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476527104
- id: gpioPortA
  type: stm32_gpioport
  bus: sysbus
  base_address: 1476526080
- id: rtc
  type: stm32f4_rtc
  bus: sysbus
  base_address: 1476411392
- id: spi4
  type: stm32h7_spi
  bus: sysbus
  base_address: 1073820672
- id: i2c4
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1476402176
- id: lpuart1
  type: stm32f7_usart
  bus: sysbus
  base_address: 1476398080
- id: syscfg
  type: stm32_syscfg
  bus: sysbus
  base_address: 1476396032
- id: dma2d
  type: stm32dma2d
  bus: sysbus
  base_address: 1375735808
- id: ltdc
  type: stm32ltdc
  bus: sysbus
  base_address: 1342181376
- id: adcM1S2
  type: stm32f0_adc
  bus: sysbus
  base_address: 1073881088
- id: rng
  type: stm32f4_rng
  bus: sysbus
  base_address: 1208096768
- id: dma2
  type: stm32dma
  bus: sysbus
  base_address: 1073873920
- id: dma1
  type: stm32dma
  bus: sysbus
  base_address: 1073872896
- id: dmamux1
  type: stm32_dmamux
  bus: sysbus
  base_address: 1073874944
- id: timer17
  type: stm32_timer
  bus: sysbus
  base_address: 1073825792
- id: timer16
  type: stm32_timer
  bus: sysbus
  base_address: 1073824768
- id: timer15
  type: stm32_timer
  bus: sysbus
  base_address: 1073823744
- id: usart6
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073812480
- id: usart1
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073811456
- id: timer8
  type: stm32_timer
  bus: sysbus
  base_address: 1073808384
- id: timer1
  type: stm32_timer
  bus: sysbus
  base_address: 1073807360
- id: uart8
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073773568
- id: uart7
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073772544
- id: i2c3
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1073765376
- id: i2c2
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1073764352
- id: i2c1
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1073763328
- id: uart5
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073762304
- id: uart4
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073761280
- id: usart3
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073760256
- id: usart2
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073759232
- id: timer14
  type: stm32_timer
  bus: sysbus
  base_address: 1073750016
- id: timer13
  type: stm32_timer
  bus: sysbus
  base_address: 1073748992
- id: timer12
  type: stm32_timer
  bus: sysbus
  base_address: 1073747968
- id: timer7
  type: stm32_timer
  bus: sysbus
  base_address: 1073746944
- id: timer6
  type: stm32_timer
  bus: sysbus
  base_address: 1073745920
- id: timer5
  type: stm32_timer
  bus: sysbus
  base_address: 1073744896
- id: timer4
  type: stm32_timer
  bus: sysbus
  base_address: 1073743872
- id: timer3
  type: stm32_timer
  bus: sysbus
  base_address: 1073742848
- id: timer2
  type: stm32_timer
  bus: sysbus
  base_address: 1073741824
- id: fdcan1
  type: mcan
  bus: sysbus
  base_address: 1073782784
- id: fdcan2
  type: mcan
  bus: sysbus
  base_address: 1073783808
- id: canMessageRAM
  type: arraymemory
  bus: sysbus
  base_address: 1073785856
- id: rcc
  type: stm32h7_rcc
  bus: sysbus
  base_address: 1476543488
- id: crc
  type: stm32_crc
  bus: sysbus
  base_address: 1476545536
- id: lptimer1
  type: stm32l0_lptimer
  bus: sysbus
  base_address: 1073751040
- id: lptimer2
  type: stm32l0_lptimer
  bus: sysbus
  base_address: 1476404224
- id: lptimer3
  type: stm32l0_lptimer
  bus: sysbus
  base_address: 1476405248
- id: lptimer4
  type: stm32l0_lptimer
  bus: sysbus
  base_address: 1476406272
- id: lptimer5
  type: stm32l0_lptimer
  bus: sysbus
  base_address: 1476407296
- id: watchdog
  type: stm32_independentwatchdog
  bus: sysbus
  base_address: 1476413440
- id: hsem
  type: stm32h7_hardwaresemaphore
  bus: sysbus
  base_address: 1476551680
- id: qspi
  type: stm32h7_quadspi
  bus: sysbus
  base_address: 1375752192
- id: sdmmc
  type: stm32hsdmmc
  bus: sysbus
  base_address: 1375760384
