# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: stm32l552
arch: arm
flash:
  base: 134217728
  size: 524288B
ram:
  base: 536870912
  size: 196608B
peripherals:
- id: spi1
  type: stm32spi
  bus: sysbus
  base_address: 1073819648
- id: spi2
  type: stm32spi
  bus: sysbus
  base_address: 1073756160
- id: spi3
  type: stm32spi
  bus: sysbus
  base_address: 1073757184
- id: usart1
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073821696
- id: usart2
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073759232
- id: usart3
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073760256
- id: uart4
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073761280
- id: uart5
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073762304
- id: lpuart1
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073774592
- id: gpioPortA
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107427328
- id: gpioPortB
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107428352
- id: gpioPortC
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107429376
- id: gpioPortD
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107430400
- id: gpioPortE
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107431424
- id: gpioPortF
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107432448
- id: gpioPortG
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107433472
- id: gpioPortH
  type: stm32_gpioport
  bus: sysbus
  base_address: 1107434496
- id: dma1
  type: stm32ldma
  bus: sysbus
  base_address: 1073872896
- id: i2c1
  type: stm32f1_i2c
  bus: sysbus
  base_address: 1073763328
- id: timer1
  type: stm32_timer
  bus: sysbus
  base_address: 1073818624
- id: timer2
  type: stm32_timer
  bus: sysbus
  base_address: 1073741824
- id: timer3
  type: stm32_timer
  bus: sysbus
  base_address: 1073742848
- id: timer4
  type: stm32_timer
  bus: sysbus
  base_address: 1073743872
- id: timer5
  type: stm32_timer
  bus: sysbus
  base_address: 1073744896
- id: timer6
  type: stm32_timer
  bus: sysbus
  base_address: 1073745920
- id: timer7
  type: stm32_timer
  bus: sysbus
  base_address: 1073746944
- id: timer8
  type: stm32_timer
  bus: sysbus
  base_address: 1073820672
- id: timer15
  type: stm32_timer
  bus: sysbus
  base_address: 1073823744
- id: timer16
  type: stm32_timer
  bus: sysbus
  base_address: 1073824768
- id: timer17
  type: stm32_timer
  bus: sysbus
  base_address: 1073825792
