# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: stm32f7_discovery-bb
arch: arm
flash:
  base: 134217728
  size: 2097152B
ram:
  base: 536870912
  size: 393216B
peripherals:
- id: phy
  type: ethernetphysicallayer
  bus: ethernet
  base_address: 0
- id: phy1
  type: ethernetphysicallayer
  bus: ethernet
  base_address: 1
- id: touchscreen
  type: ft5336
  bus: i2c3
  base_address: 56
- id: usart1
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073811456
- id: usart2
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073759232
- id: usart3
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073760256
- id: usart6
  type: stm32f7_usart
  bus: sysbus
  base_address: 1073812480
- id: can1
  type: stmcan
  bus: sysbus
  base_address: 1073767424
- id: gpioPortA
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073872896
- id: gpioPortB
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073873920
- id: gpioPortC
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073874944
- id: gpioPortD
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073875968
- id: gpioPortE
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073876992
- id: gpioPortF
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073878016
- id: gpioPortG
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073879040
- id: gpioPortH
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073880064
- id: gpioPortI
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073881088
- id: gpioPortJ
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073882112
- id: gpioPortK
  type: stm32_gpioport
  bus: sysbus
  base_address: 1073883136
- id: ethernet
  type: synopsysethernetmac
  bus: sysbus
  base_address: 1073905664
- id: spi1
  type: stm32spi
  bus: sysbus
  base_address: 1073819648
- id: spi2
  type: stm32spi
  bus: sysbus
  base_address: 1073756160
- id: spi3
  type: stm32spi
  bus: sysbus
  base_address: 1073757184
- id: dma1
  type: stm32dma
  bus: sysbus
  base_address: 1073897472
- id: dma2
  type: stm32dma
  bus: sysbus
  base_address: 1073898496
- id: ltdc
  type: stm32ltdc
  bus: sysbus
  base_address: 1073833984
- id: dma2d
  type: stm32dma2d
  bus: sysbus
  base_address: 1073917952
- id: i2c1
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1073763328
- id: i2c2
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1073764352
- id: i2c3
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1073765376
- id: i2c4
  type: stm32f7_i2c
  bus: sysbus
  base_address: 1073766400
- id: syscfg
  type: stm32_syscfg
  bus: sysbus
  base_address: 1073821696
- id: lptim1Isr
  type: pythonperipheral
  bus: sysbus
  base_address: 1073751040
- id: rtc
  type: stm32f4_rtc
  bus: sysbus
  base_address: 1073752064
- id: rcc
  type: stm32f4_rcc
  bus: sysbus
  base_address: 1073887232
- id: rng
  type: stm32f4_rng
  bus: sysbus
  base_address: 1342572544
- id: pwrCr1
  type: pythonperipheral
  bus: sysbus
  base_address: 1073770496
- id: pwrCsr1
  type: pythonperipheral
  bus: sysbus
  base_address: 1073770500
- id: sdmmc
  type: stm32fsdmmc
  bus: sysbus
  base_address: 1073818624
- id: timer1
  type: stm32_timer
  bus: sysbus
  base_address: 1073807360
- id: timer2
  type: stm32_timer
  bus: sysbus
  base_address: 1073741824
- id: timer3
  type: stm32_timer
  bus: sysbus
  base_address: 1073742848
- id: timer4
  type: stm32_timer
  bus: sysbus
  base_address: 1073743872
- id: timer5
  type: stm32_timer
  bus: sysbus
  base_address: 1073744896
- id: timer6
  type: stm32_timer
  bus: sysbus
  base_address: 1073745920
- id: timer7
  type: stm32_timer
  bus: sysbus
  base_address: 1073746944
- id: timer8
  type: stm32_timer
  bus: sysbus
  base_address: 1073808384
- id: timer9
  type: stm32_timer
  bus: sysbus
  base_address: 1073823744
- id: timer10
  type: stm32_timer
  bus: sysbus
  base_address: 1073824768
- id: timer11
  type: stm32_timer
  bus: sysbus
  base_address: 1073825792
- id: timer12
  type: stm32_timer
  bus: sysbus
  base_address: 1073747968
- id: timer13
  type: stm32_timer
  bus: sysbus
  base_address: 1073748992
- id: timer14
  type: stm32_timer
  bus: sysbus
  base_address: 1073750016
