# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: tegra3
arch: arm
flash:
  base: 134217728
  size: 1073741824B
ram:
  base: 536870912
  size: 1073741824B
peripherals:
- id: uart0
  type: ns16550
  bus: sysbus
  base_address: 1879072768
- id: uart1
  type: ns16550
  bus: sysbus
  base_address: 1879072832
- id: uart2
  type: ns16550
  bus: sysbus
  base_address: 1879073280
- id: uart3
  type: ns16550
  bus: sysbus
  base_address: 1879073536
- id: uart4
  type: ns16550
  bus: sysbus
  base_address: 1879061504
- id: dmaHost1xA
  type: tegradmahost1x
  bus: sysbus
  base_address: 1342242816
- id: dmaHost1xB
  type: tegradmahost1x
  bus: sysbus
  base_address: 1342193664
- id: privateTimer
  type: arm_privatetimer
  bus: sysbus
  base_address: 1342440960
- id: tmr1
  type: tegratimer
  bus: sysbus
  base_address: 1610633216
- id: tmr2
  type: tegratimer
  bus: sysbus
  base_address: 1610633224
- id: tmrUs
  type: tegrausectimer
  bus: sysbus
  base_address: 1610633232
- id: tmr3
  type: tegratimer
  bus: sysbus
  base_address: 1610633296
- id: tmr4
  type: tegratimer
  bus: sysbus
  base_address: 1610633304
- id: pl310
  type: pl310
  bus: sysbus
  base_address: 1342451712
- id: usbEhci1
  type: ehcihostcontroller
  bus: sysbus
  base_address: 2097152000
- id: usbEhci2
  type: ehcihostcontroller
  bus: sysbus
  base_address: 2097168384
- id: usbEhci3
  type: ehcihostcontroller
  bus: sysbus
  base_address: 2097184768
- id: apbDma
  type: tegradma
  bus: sysbus
  base_address: 1610653696
- id: i2c1
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879097344
- id: i2c2
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879098368
- id: i2c3
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879098624
- id: i2c4
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879099136
- id: i2c5
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879101440
- id: fb0
  type: tegradisplay
  bus: sysbus
  base_address: 1411383296
- id: fb1
  type: tegradisplay
  bus: sysbus
  base_address: 1411645440
- id: syncPts
  type: tegrasyncpts
  bus: sysbus
  base_address: 1342177280
- id: nvPaPmcBase
  type: pythonperipheral
  bus: sysbus
  base_address: 1879106560
- id: pgUpTag0
  type: pythonperipheral
  bus: sysbus
  base_address: 1610612736
- id: memoryControllerMemsize
  type: pythonperipheral
  bus: sysbus
  base_address: 1879110672
- id: nandHack1
  type: pythonperipheral
  bus: sysbus
  base_address: 1879080960
- id: nandHackNandStatus
  type: pythonperipheral
  bus: sysbus
  base_address: 1879080964
- id: nandHackIsr
  type: pythonperipheral
  bus: sysbus
  base_address: 1879080968
- id: oscFreqDetStatus
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637404
- id: pllC
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637440
- id: pllM
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637456
- id: pllP
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637472
- id: superclock1
  type: pythonperipheral
  bus: sysbus
  base_address: 1610638184
- id: superclock2
  type: pythonperipheral
  bus: sysbus
  base_address: 1610638192
- id: sdmmc3
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637756
- id: clkSrc
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637572
- id: clkSrcA
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637604
- id: clkSrc_
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637608
- id: pllSomething2
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637520
- id: pllSomething3
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637532
- id: pllSomething
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637316
- id: test111
  type: pythonperipheral
  bus: sysbus
  base_address: 1879110148
- id: apbMiscGpHidrev0
  type: pythonperipheral
  bus: sysbus
  base_address: 1879050244
- id: clockHack
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637344
- id: clkRstControllerSclkBurstpolicy0
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637352
- id: kfuseHack
  type: pythonperipheral
  bus: sysbus
  base_address: 1879111680
- id: kfuseHack2
  type: pythonperipheral
  bus: sysbus
  base_address: 1879112188
- id: kfuseSkuInfo
  type: pythonperipheral
  bus: sysbus
  base_address: 1879111952
- id: kfuseTestProgRevision
  type: pythonperipheral
  bus: sysbus
  base_address: 1879111976
- id: fuseSpeedoCalib
  type: pythonperipheral
  bus: sysbus
  base_address: 1879111956
- id: pwrGateStatus
  type: pythonperipheral
  bus: sysbus
  base_address: 1879106616
- id: miscDebug
  type: pythonperipheral
  bus: sysbus
  base_address: 1879048212
- id: tegraId
  type: pythonperipheral
  bus: sysbus
  base_address: 1879050336
- id: usbHub
  type: usbhub
  bus: usbEhci2
  base_address: 1
- id: usbMouse
  type: usbmouse
  bus: usbHub
  base_address: 2
- id: usbKeyboard
  type: usbkeyboard
  bus: usbHub
  base_address: 1
