# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: tegra2
arch: arm
flash:
  base: 134217728
  size: 536870912B
ram:
  base: 536870912
  size: 536870912B
peripherals:
- id: uart0
  type: ns16550
  bus: sysbus
  base_address: 1879072768
- id: uart3
  type: ns16550
  bus: sysbus
  base_address: 1879073536
- id: dmaHost1xA
  type: tegradmahost1x
  bus: sysbus
  base_address: 1342242816
- id: dmaHost1xB
  type: tegradmahost1x
  bus: sysbus
  base_address: 1342193664
- id: privateTimer
  type: arm_privatetimer
  bus: sysbus
  base_address: 1342440960
- id: tmr1
  type: tegratimer
  bus: sysbus
  base_address: 1610633216
- id: tmr2
  type: tegratimer
  bus: sysbus
  base_address: 1610633224
- id: tmrUs
  type: tegrausectimer
  bus: sysbus
  base_address: 1610633232
- id: tmr3
  type: tegratimer
  bus: sysbus
  base_address: 1610633296
- id: tmr4
  type: tegratimer
  bus: sysbus
  base_address: 1610633304
- id: pl310
  type: pl310
  bus: sysbus
  base_address: 1342451712
- id: scu
  type: armsnoopcontrolunit
  bus: sysbus
  base_address: 4176478208
- id: usbEhci1
  type: ehcihostcontroller
  bus: sysbus
  base_address: 3305111552
- id: usbEhci2
  type: ehcihostcontroller
  bus: sysbus
  base_address: 3305127936
- id: usbEhci3
  type: ehcihostcontroller
  bus: sysbus
  base_address: 3305144320
- id: apbDma
  type: tegradma
  bus: sysbus
  base_address: 1610653696
- id: i2c1
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879097344
- id: i2c2
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879098368
- id: i2c3
  type: tegrai2ccontroller
  bus: sysbus
  base_address: 1879098624
- id: fb1
  type: tegradisplay
  bus: sysbus
  base_address: 1411645440
- id: syncPts
  type: tegrasyncpts
  bus: sysbus
  base_address: 1342177280
- id: dvc
  type: tegradvc
  bus: sysbus
  base_address: 1879101440
- id: pwrGateStatus
  type: pythonperipheral
  bus: sysbus
  base_address: 1879106616
- id: memoryControllerMemsize
  type: pythonperipheral
  bus: sysbus
  base_address: 1879110672
- id: nandHack1
  type: pythonperipheral
  bus: sysbus
  base_address: 1879080960
- id: nandHackNandStatus
  type: pythonperipheral
  bus: sysbus
  base_address: 1879080964
- id: nanHackIsr
  type: pythonperipheral
  bus: sysbus
  base_address: 1879080968
- id: oscFreqDetStatus
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637404
- id: pllC
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637440
- id: pllM
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637456
- id: pllP
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637472
- id: clkSrc
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637572
- id: apbMiscGpHidrev0
  type: pythonperipheral
  bus: sysbus
  base_address: 1879050244
- id: clockHack
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637344
- id: clkRstControllerSclkBurstPolicy0
  type: pythonperipheral
  bus: sysbus
  base_address: 1610637352
- id: kfuseHack
  type: pythonperipheral
  bus: sysbus
  base_address: 1879111680
- id: usbHub
  type: usbhub
  bus: usbEhci2
  base_address: 1
- id: usbMouse
  type: usbmouse
  bus: usbHub
  base_address: 2
- id: usbKeyboard
  type: usbkeyboard
  bus: usbHub
  base_address: 1
