# LabWired - Firmware Simulation Platform
# Copyright (C) 2026 Andrii Shylenko
#
# This software is released under the MIT License.
# See the LICENSE file in the project root for full license information.

name: tock_veer_el2_sim
arch: arm
flash:
  base: 0
  size: 5242880B
ram:
  base: 543162368
  size: 3145728B
peripherals: []
