#!/usr/bin/env python3
"""Regenerate crates/core/src/bus/embedded_descriptors.rs.

Embeds the configs/peripherals descriptors a chip YAML actually REFERENCES, so
SystemBus::from_config resolves them without a filesystem (wasm32 has no
std::fs). A descriptor missing here fails ONLY in the browser, at runtime, on
the lab that needs it — which is why this file must never be maintained by
hand: rp2040/esp32s3/nrf52832 were all silently absent while their chip YAMLs
referenced them. The embedded_descriptor_registry_is_complete test (native, has
fs) fails the build when this file goes stale.

REFERENCED, not "every file on disk". These YAMLs are `include_str!`d into every
binary, wasm included, and configs/peripherals holds far more than any chip
loads: an SVD import emits a descriptor per vendor peripheral, while a chip YAML
wires only the blocks it models. Embedding the whole tree put megabytes of YAML
that nothing can ever look up into the browser download. Native builds still
fall back to from_file, so an unreferenced descriptor stays usable on the CLI;
it just does not ride along in the wasm.

Two keys count as a reference, and they are not interchangeable:
  config.path         -- a `type: declarative` peripheral's real MODEL
  config.debug_schema -- decode metadata only, for a native peripheral

Usage: python3 scripts/gen_embedded_descriptors.py   (from the repo root)
"""

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PERIPHERALS = ROOT / "configs" / "peripherals"
OUT = ROOT / "crates" / "core" / "src" / "bus" / "embedded_descriptors.rs"

HEADER = '''\
// AUTO-GENERATED by scripts/gen_embedded_descriptors.py — do not edit by hand.
// Embeds the configs/peripherals descriptors that a chip YAML references, so
// SystemBus::from_config can resolve them WITHOUT a filesystem (wasm32 has no
// std::fs). Native builds still fall back to from_file for any path not
// embedded here. Keyed by the suffix after 'peripherals/'.
//
// Referenced, not every file on disk: these are include_str!'d into the wasm
// download, and an SVD import emits a descriptor per vendor peripheral while a
// chip wires only the blocks it models. Embedding the unreferenced remainder
// shipped megabytes of YAML nothing could ever look up.
//
// Refresh: python3 scripts/gen_embedded_descriptors.py
// Guard: embedded_descriptor_registry_is_complete (native) fails when a
// referenced descriptor is missing here, and when an embedded one is
// referenced by nothing — the first breaks a lab, the second bloats every
// browser download.

/// Every embedded descriptor, sorted by key so `lookup` can binary-search it.
static DESCRIPTORS: &[(&str, &str)] = &[
'''

FOOTER = '''\
];

/// Look up an embedded descriptor by its chip-YAML `path:` value
/// (e.g. `../peripherals/esp32c3/gpio.yaml`). Returns the YAML text if embedded.
pub fn lookup(descriptor_path: &str) -> Option<&'static str> {
    // Normalize: take everything after the last "peripherals/".
    let key = descriptor_path
        .rsplit_once("peripherals/")
        .map(|(_, k)| k)
        .unwrap_or(descriptor_path);
    DESCRIPTORS
        .binary_search_by(|(k, _)| k.cmp(&key))
        .ok()
        .map(|i| DESCRIPTORS[i].1)
}

#[cfg(test)]
mod tests {
    use super::{lookup, DESCRIPTORS};

    /// The table must stay sorted and duplicate-free: `lookup` binary-searches
    /// it, so a hand edit that breaks either invariant would silently miss keys.
    #[test]
    fn embedded_descriptor_table_is_sorted_and_unique() {
        let mut previous: Option<&str> = None;
        for (key, _) in DESCRIPTORS {
            assert!(
                previous.is_none_or(|p| p < *key),
                "embedded descriptor table is not sorted/unique at {key:?}"
            );
            previous = Some(key);
        }
    }

    /// Descriptor keys a chip YAML can actually ask for at runtime.
    ///
    /// `config.path` loads a declarative peripheral's real MODEL;
    /// `config.debug_schema` supplies decode metadata for a native one. Both
    /// are resolved through `lookup` in the browser, so both must be embedded.
    fn referenced_keys() -> std::collections::BTreeSet<String> {
        let chips = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../configs/chips");
        let mut keys = std::collections::BTreeSet::new();
        for entry in std::fs::read_dir(&chips).expect("read configs/chips") {
            let path = entry.expect("dir entry").path();
            if path.extension().is_none_or(|e| e != "yaml") {
                continue;
            }
            let text = std::fs::read_to_string(&path).expect("read chip yaml");
            for line in text.lines() {
                let Some((key, value)) = line.split_once(':') else {
                    continue;
                };
                let key = key.trim();
                if key != "path" && key != "debug_schema" {
                    continue;
                }
                let value = value.trim().trim_matches('"');
                if let Some((_, k)) = value.rsplit_once("peripherals/") {
                    keys.insert(k.to_string());
                }
            }
        }
        keys
    }

    /// Every descriptor a chip references must be embedded: a miss compiles
    /// fine and runs fine natively, then breaks ONLY in the browser, on the lab
    /// that needs it. Regenerate with scripts/gen_embedded_descriptors.py.
    #[test]
    fn embedded_descriptor_registry_is_complete() {
        let missing: Vec<_> = referenced_keys()
            .into_iter()
            .filter(|k| lookup(k).is_none())
            .collect();
        assert!(
            missing.is_empty(),
            "chip YAMLs reference descriptors that are not embedded \
             (breaks wasm labs): {missing:?}\n\
             run: python3 scripts/gen_embedded_descriptors.py"
        );
    }

    /// ...and nothing else may be embedded. These YAMLs are `include_str!`d
    /// into every binary including wasm, and configs/peripherals holds far more
    /// than any chip loads — an SVD import emits a descriptor per vendor
    /// peripheral, a chip YAML wires only the blocks it models. Embedding the
    /// remainder put megabytes of YAML that nothing can ever look up into the
    /// browser download. Unreferenced descriptors stay on disk and still work
    /// natively through the from_file fallback.
    #[test]
    fn embedded_descriptor_registry_carries_no_dead_weight() {
        let root =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../configs/peripherals");
        let referenced = referenced_keys();
        let mut dead = Vec::new();
        let mut stack = vec![root.clone()];
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).expect("read configs/peripherals") {
                let path = entry.expect("dir entry").path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|e| e == "yaml") {
                    let key = path
                        .strip_prefix(&root)
                        .expect("under peripherals root")
                        .to_string_lossy()
                        .into_owned();
                    if lookup(&key).is_some() && !referenced.contains(&key) {
                        dead.push(key);
                    }
                }
            }
        }
        dead.sort();
        assert!(
            dead.is_empty(),
            "descriptors embedded but referenced by no chip YAML \
             (dead weight in every browser download): {dead:?}\n\
             run: python3 scripts/gen_embedded_descriptors.py"
        );
    }
}
'''


CHIPS = ROOT / "configs" / "chips"
# `config.path` loads a declarative peripheral's real model; `config.debug_schema`
# supplies decode metadata for a native one. Both make a descriptor reachable at
# runtime, so both must be embedded.
REF_KEY = re.compile(r"(?:path|debug_schema):\s*\"?([^\"\s]+\.yaml)\"?")


def referenced_keys() -> set[str]:
    """Descriptor keys some chip YAML can actually ask for at runtime."""
    keys = set()
    for chip in sorted(CHIPS.glob("*.yaml")):
        for value in REF_KEY.findall(chip.read_text()):
            if "peripherals/" in value:
                keys.add(value.rsplit("peripherals/", 1)[1])
    return keys


def main() -> None:
    on_disk = {p.relative_to(PERIPHERALS).as_posix() for p in PERIPHERALS.rglob("*.yaml")}
    wanted = referenced_keys()
    # A reference with no file is the failure this script exists to prevent, and
    # it must not be papered over: include_str! on a missing path fails the build
    # loudly, which is the right outcome, but say which chip is broken first.
    missing = sorted(wanted - on_disk)
    if missing:
        raise SystemExit(
            "chip YAML references descriptors that do not exist: " + ", ".join(missing)
        )
    keys = sorted(wanted)
    entries = [
        f'    ("{key}", include_str!(\n'
        f'        "../../../../configs/peripherals/{key}"\n'
        f"    )),"
        for key in keys
    ]
    OUT.write_text(HEADER + "\n".join(entries) + "\n" + FOOTER)
    # rustfmt owns the final shape (line collapsing etc.) so the emitted file
    # is byte-stable under `cargo fmt --check` regardless of fmt config.
    subprocess.run(["rustfmt", "--edition", "2021", str(OUT)], check=True)
    embedded = sum((PERIPHERALS / k).stat().st_size for k in keys)
    total = sum((PERIPHERALS / k).stat().st_size for k in on_disk)
    print(
        f"embedded {len(keys)}/{len(on_disk)} descriptors "
        f"({embedded / 1e6:.2f} MB of {total / 1e6:.2f} MB on disk) "
        f"into {OUT.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
