#!/usr/bin/env python3
"""Generate SYSTIMER register offsets from the checked-in ESP32-S3 SVD.

Usage (from core repo root):
  python3 scripts/gen_esp_systimer_regs.py

ESP32-C3 uses the same SYSTIMER IP for freerunning/millis offsets; the S3 SVD
is the superset (includes REAL_TARGET*).
"""
from __future__ import annotations

from pathlib import Path
import xml.etree.ElementTree as ET
import sys

ROOT = Path(__file__).resolve().parents[1]
SVD = ROOT / "tests/fixtures/svd/esp32s3.svd"
OUT = ROOT / "crates/core/src/peripherals/esp32s3/systimer_regs.rs"

POLL_NAMES = {
    "UNIT0_OP",
    "UNIT1_OP",
    "UNIT0_VALUE_HI",
    "UNIT0_VALUE_LO",
    "UNIT1_VALUE_HI",
    "UNIT1_VALUE_LO",
}


def main() -> int:
    root = ET.parse(SVD).getroot()
    peri = None
    for p in root.iter("peripheral"):
        if (p.findtext("name") or "") == "SYSTIMER":
            peri = p
            break
    if peri is None:
        print("SYSTIMER peripheral not found in", SVD, file=sys.stderr)
        return 1

    regs: list[tuple[str, int]] = []
    for reg in peri.findall("./registers/register"):
        name = reg.findtext("name")
        off = reg.findtext("addressOffset")
        if not name or off is None:
            continue
        regs.append((name, int(off, 0)))

    lines = [
        "// @generated by scripts/gen_esp_systimer_regs.py from tests/fixtures/svd/esp32s3.svd",
        "// DO NOT EDIT BY HAND — re-run: python3 scripts/gen_esp_systimer_regs.py",
        "//",
        "// ESP32-C3 SYSTIMER is the same IP block (identical freerunning offsets);",
        "// S3 SVD is the superset (includes REAL_TARGET*).",
        "",
        "//! SYSTIMER register offsets derived from the checked-in SVD.",
        "",
    ]
    for name, off in regs:
        lines.append(f"pub const {name}: u64 = 0x{off:X};")
    lines.append("")
    lines.append("/// Freerunning snapshot path (esp_timer / Arduino millis).")
    lines.append("/// Derived from the named SVD offsets above.")
    lines.append("pub const FREERUNNING_POLL: &[u64] = &[")
    for name, _ in regs:
        if name in POLL_NAMES:
            lines.append(f"    {name},")
    lines.append("];")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(regs)} registers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
