#!/usr/bin/env python3
"""Regenerate crates/core/src/bus/embedded_descriptors.rs.

Embeds EVERY configs/peripherals/**/*.yaml into the binary so
SystemBus::from_config resolves declarative descriptors without a filesystem
(wasm32 has no std::fs). A descriptor missing here fails ONLY in the browser,
at runtime, on the lab that needs it — which is why this file must never be
maintained by hand: rp2040/esp32s3/nrf52832 were all silently absent while
their chip YAMLs referenced them. The embedded_descriptor_registry_is_complete
test (native, has fs) fails the build when this file goes stale.

Usage: python3 scripts/gen_embedded_descriptors.py   (from the repo root)
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PERIPHERALS = ROOT / "configs" / "peripherals"
OUT = ROOT / "crates" / "core" / "src" / "bus" / "embedded_descriptors.rs"

HEADER = '''\
// AUTO-GENERATED by scripts/gen_embedded_descriptors.py — do not edit by hand.
// Embeds every configs/peripherals/**/*.yaml so SystemBus::from_config can
// resolve declarative descriptors WITHOUT a filesystem (wasm32 has no
// std::fs). Native builds still fall back to from_file for any path not
// embedded here. Keyed by the suffix after 'peripherals/'.
//
// Refresh: python3 scripts/gen_embedded_descriptors.py
// Guard: the embedded_descriptor_registry_is_complete test (native) fails
// when a descriptor exists on disk but is missing here.

/// Look up an embedded descriptor by its chip-YAML `path:` value
/// (e.g. `../peripherals/esp32c3/gpio.yaml`). Returns the YAML text if embedded.
pub fn lookup(descriptor_path: &str) -> Option<&'static str> {
    // Normalize: take everything after the last "peripherals/".
    let key = descriptor_path
        .rsplit_once("peripherals/")
        .map(|(_, k)| k)
        .unwrap_or(descriptor_path);
    match key {
'''

FOOTER = '''\
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::lookup;

    /// Every descriptor on disk must be embedded: a miss compiles fine and
    /// runs fine natively, then breaks ONLY in the browser on the lab that
    /// needs it. Regenerate with scripts/gen_embedded_descriptors.py.
    #[test]
    fn embedded_descriptor_registry_is_complete() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../configs/peripherals");
        let mut missing = Vec::new();
        let mut stack = vec![root.clone()];
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).expect("read configs/peripherals") {
                let path = entry.expect("dir entry").path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|e| e == "yaml") {
                    let key = path
                        .strip_prefix(&root)
                        .expect("under peripherals root")
                        .to_string_lossy()
                        .into_owned();
                    if lookup(&key).is_none() {
                        missing.push(key);
                    }
                }
            }
        }
        missing.sort();
        assert!(
            missing.is_empty(),
            "descriptors on disk but not embedded (breaks wasm labs): {missing:?}\\n\\
             run: python3 scripts/gen_embedded_descriptors.py"
        );
    }
}
'''


def main() -> None:
    keys = sorted(
        p.relative_to(PERIPHERALS).as_posix()
        for p in PERIPHERALS.rglob("*.yaml")
    )
    arms = []
    for key in keys:
        arms.append(
            f'        "{key}" => Some(include_str!(\n'
            f'            "../../../../configs/peripherals/{key}"\n'
            f"        )),"
        )
    OUT.write_text(HEADER + "\n".join(arms) + "\n" + FOOTER)
    print(f"embedded {len(keys)} descriptors into {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
