#!/usr/bin/env python3
"""
Generate docs/boards/VALIDATION_STATUS.md from validation/manifest.yaml and
enforce the no-silent-decay rule.

The board docs drift; this generated table does not. It is the single
machine-checked view of what is actually validated, against which silicon, and
on what date — plus an automated DRIFT gate that catches the case where a
peripheral model changed AFTER the board's last silicon capture.

Modes
-----
  (default)      regenerate docs/boards/VALIDATION_STATUS.md in place
  --check        regenerate to memory and diff against the committed file;
                 exit 1 if they differ (run this in CI so the doc cannot go stale)
  --drift        exit 1 if any silicon-tier board has DRIFTED past its drift_ack
  (you normally run CI with BOTH:  --check --drift)

Drift
-----
For each board with `silicon.last_capture`, the newest git commit date across
`models` is compared to the capture date. If newer, the board has drifted. A
dated `drift_ack` (>= the newest model date) is an explicit human acknowledgement
that keeps it green; any later model change re-breaks the gate.

Needs PyYAML (pip install pyyaml) and a full-history checkout (fetch-depth: 0)
so `git log -- <path>` resolves dates.
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required — `pip install pyyaml`", file=sys.stderr)
    sys.exit(2)

CORE_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = CORE_ROOT / "validation" / "manifest.yaml"
OUT_DOC = CORE_ROOT / "docs" / "boards" / "VALIDATION_STATUS.md"

TIER_BADGE = {
    "silicon-verified": "🟢 silicon-verified",
    "silicon-smoke": "🟢 silicon-smoke",
    "sim-validated": "🔵 sim-validated (deep model, no HW diff)",
    "smoke-manual": "🟡 smoke-manual",
    "structural": "⚪ structural",
}


def newest_commit_date(paths: list[str]) -> date | None:
    """Newest committer date (YYYY-MM-DD) across the given repo paths, or None."""
    newest: date | None = None
    for rel in paths:
        target = CORE_ROOT / rel
        if not target.exists():
            # A listed model path that no longer exists is itself a manifest bug.
            print(f"WARNING: manifest model path does not exist: {rel}", file=sys.stderr)
            continue
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cI", "--", rel],
            cwd=CORE_ROOT,
            capture_output=True,
            text=True,
        )
        iso = out.stdout.strip()
        if not iso:
            continue
        d = datetime.fromisoformat(iso).date()
        if newest is None or d > newest:
            newest = d
    return newest


def as_date(v) -> date | None:
    if v is None:
        return None
    if isinstance(v, date):
        return v
    return datetime.fromisoformat(str(v)).date()


def evaluate(board: dict) -> dict:
    """Compute drift status for one board."""
    silicon = board.get("silicon")
    models = board.get("models", [])
    newest = newest_commit_date(models)
    capture = as_date(silicon["last_capture"]) if silicon else None
    ack = as_date(board.get("drift_ack"))

    drifted = bool(capture and newest and newest > capture)
    acked = bool(ack and newest and ack >= newest)
    # A board with no silicon capture cannot "drift" — it never claimed silicon.
    failing = drifted and not acked

    if not silicon:
        status = "no silicon capture"
    elif not drifted:
        status = "✅ fresh"
    elif acked:
        status = f"⚠ drift acked {ack:%Y-%m-%d} (re-capture pending)"
    else:
        status = f"✖ DRIFT — model {newest:%Y-%m-%d} > capture; RE-CAPTURE"

    return {
        "newest_model": newest,
        "capture": capture,
        "drifted": drifted,
        "failing": failing,
        "status": status,
    }


def render(manifest: dict) -> str:
    boards = manifest["boards"]
    lines: list[str] = []
    lines.append("<!-- GENERATED by scripts/generate_validation_status.py — DO NOT EDIT BY HAND.")
    lines.append("     Source of truth: validation/manifest.yaml. Regenerated and gated on every CI run. -->")
    lines.append("")
    lines.append("# Board validation status")
    lines.append("")
    lines.append(
        "Machine-generated from `validation/manifest.yaml`. CI regenerates this on "
        "every run (`--check`) and fails if a peripheral model changed after a "
        "board's last silicon capture without a dated `drift_ack` (`--drift`). "
        "Tiers: 🟢 silicon · 🟡 manual-smoke · ⚪ structural."
    )
    lines.append("")
    lines.append("| Board | Tier | Last silicon capture | Newest model | Status |")
    lines.append("|-------|------|----------------------|--------------|--------|")
    for b in boards:
        ev = evaluate(b)
        tier = TIER_BADGE.get(b["tier"], b["tier"])
        cap = f"{ev['capture']:%Y-%m-%d}" if ev["capture"] else "—"
        nm = f"{ev['newest_model']:%Y-%m-%d}" if ev["newest_model"] else "—"
        lines.append(f"| `{b['id']}` | {tier} | {cap} | {nm} | {ev['status']} |")
    lines.append("")

    # Per-board detail
    for b in boards:
        ev = evaluate(b)
        lines.append(f"## `{b['id']}` — {TIER_BADGE.get(b['tier'], b['tier'])}")
        lines.append("")
        lines.append(f"- Doc: [`{b['doc']}`]({Path(b['doc']).name})  ·  Chip: `{b['chip']}`")
        if b.get("note"):
            lines.append(f"- Note: {b['note']}")
        sil = b.get("silicon")
        if sil:
            lines.append(
                f"- Silicon: **{ev['capture']:%Y-%m-%d}** on {sil.get('probe', '?')} — {sil.get('result', '')}"
            )
        else:
            lines.append("- Silicon: none — not validated against real hardware.")
        for t in b.get("offline_tests", []):
            lines.append(f"  - offline (CI): {t}")
        lines.append(f"- Drift status: **{ev['status']}**")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if committed doc is stale")
    ap.add_argument("--drift", action="store_true", help="fail if any board drifted past its ack")
    args = ap.parse_args()

    manifest = yaml.safe_load(MANIFEST.read_text())
    rendered = render(manifest)

    rc = 0

    if args.check:
        existing = OUT_DOC.read_text() if OUT_DOC.exists() else ""
        if existing != rendered:
            # Print the actual difference. This doc is rendered partly from git
            # commit dates, so a checkout whose history differs from yours can
            # fail this gate while it passes locally — and "is out of date" on
            # its own gives a CI reader nothing to act on.
            diff = "".join(
                difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    rendered.splitlines(keepends=True),
                    fromfile=f"{OUT_DOC.name} (committed)",
                    tofile=f"{OUT_DOC.name} (regenerated here)",
                )
            )
            print(
                f"ERROR: {OUT_DOC.relative_to(CORE_ROOT)} is out of date.\n"
                "       Run: python3 scripts/generate_validation_status.py\n"
                f"{diff}",
                file=sys.stderr,
            )
            rc = 1
    elif not args.drift:
        # Pure generate mode (no gate flags): rewrite the doc in place.
        OUT_DOC.write_text(rendered)
        print(f"wrote {OUT_DOC.relative_to(CORE_ROOT)}")

    if args.drift:
        failing = [b["id"] for b in manifest["boards"] if evaluate(b)["failing"]]
        if failing:
            print(
                "ERROR: silicon validation has DRIFTED (model changed after last capture, "
                "no covering drift_ack):\n  " + "\n  ".join(failing) + "\n"
                "       Re-run the live diff and bump silicon.last_capture, or set a dated "
                "drift_ack in validation/manifest.yaml.",
                file=sys.stderr,
            )
            rc = 1

    return rc


if __name__ == "__main__":
    sys.exit(main())
