import yaml
from pathlib import Path

REPO_ROOT = Path("/home/andrii/Projects/labwired/core")

targets = [
    "acrn_x86_64", "crosslink-nx-evn", "egis_et171", "fomu", "gr712rc",
    "gr716-devboard", "gr716", "ice40up5k-mdp-evn", "kendryte_k210", "litex_ibex",
    "litex_microwatt", "litex_nexys_video_vexriscv_linux", "litex_tock",
    "litex_vexriscv_linux", "litex_vexriscv_tftp", "litex_vexriscv_verilated_cfu",
    "litex_vexriscv_verilated_liteuart", "mpc5567", "picosoc", "tock_veer_el2_sim",
    "verilated_ibex", "x86"
]

for t in targets:
    # 1. Ensure onboarding YAML exists (if missing, maybe it's generated by CI, but let's make it)
    onboarding_path = REPO_ROOT / f"configs/onboarding/{t}.yaml"
    if not onboarding_path.exists():
        onboarding = {
            "name": t,
            "description": f"Auto-generated draft for {t}",
            "pass_rate": 0,
            "verified": False,
            "system": f"systems/onboarding/{t}.yaml"
        }
        onboarding_path.parent.mkdir(parents=True, exist_ok=True)
        onboarding_path.write_text(yaml.dump(onboarding, sort_keys=False))

    # 2. Ensure system manifest exists
    system_path = REPO_ROOT / f"configs/systems/onboarding/{t}.yaml"
    if not system_path.exists():
        system = {
            "name": t,
            "machine": {
                "chip": f"chips/onboarding/{t}.yaml"
            }
        }
        system_path.parent.mkdir(parents=True, exist_ok=True)
        system_path.write_text(yaml.dump(system, sort_keys=False))

    # 3. Ensure chip descriptor exists and has RAM/FLASH
    chip_path = REPO_ROOT / f"configs/chips/onboarding/{t}.yaml"
    chip = {}
    if chip_path.exists():
        chip = yaml.safe_load(chip_path.read_text()) or {}
    
    chip["name"] = t
    if "flash" not in chip or not chip["flash"].get("base"):
        chip["flash"] = {"base": 0x20000000, "size": 1048576}
    if "ram" not in chip or not chip["ram"].get("base"):
        chip["ram"] = {"base": 0x40000000, "size": 262144}
    
    chip_path.parent.mkdir(parents=True, exist_ok=True)
    chip_path.write_text(yaml.dump(chip, sort_keys=False))

print("All missing manifests patched!")
