#!/usr/bin/env bash
# Regenerate EVERY committed artifact that is derived from repo state.
#
# Why this exists: these generators were discovered one red build at a time.
# A model change would land, CI would fail on a stale generated file, that one
# would get regenerated, and the next push would fail on a different one. Four
# separate files were found that way in a single session, and a survey then
# turned up nine generator scripts in total — of which only two had a --check
# staleness flag and four were not referenced by any workflow. So a generated
# artifact could drift indefinitely with nothing to catch it, including
# checked-in Rust source.
#
# Pair this with `git diff --exit-code` in CI (see the reliability workflow):
# running the whole set and asserting a clean tree gives staleness detection for
# ALL of them at once — including generators added after this script is written,
# provided they are registered here. That is strictly better than adding a
# bespoke --check flag to each script.
#
# Usage:
#   scripts/regen-all.sh           # regenerate everything cheap
#   scripts/regen-all.sh --matrix  # also re-run the Tier-1 matrix (slow: builds
#                                  # the sim and executes every fixture)
#
# NOT included, deliberately — these are CI-input-driven tools, not artifact
# regenerators, and they require arguments or inputs that do not exist in a
# clean checkout:
#   gen_debug_schemas.py                 (needs --svd)
#   generate_onboarding_scoreboard.py    (needs --metrics-root/--markdown-out)
#   generate_coverage_matrix_scoreboard.py (needs out/coverage-matrix)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

want_matrix=0
[ "${1:-}" = "--matrix" ] && want_matrix=1

run() {
  echo "==> $*"
  "$@"
}

# The Tier-1 matrix is the input to the scoreboard, so it must come first when
# requested. It is opt-in because it builds the simulator and runs every fixture.
if [ "$want_matrix" = "1" ]; then
  run cargo build --release -p labwired-cli
  run ./target/release/labwired tier1-matrix --json-out docs/coverage/tier1-matrix.json
fi

run python3 scripts/generate_tier1_scoreboard.py
run python3 scripts/generate_validation_status.py
run python3 scripts/generate_firmware_exercise_matrix.py
run python3 scripts/generate_compat_matrix.py
run python3 scripts/gen_embedded_descriptors.py
run python3 scripts/gen_esp_systimer_regs.py

# The conformance scoreboard is regenerated by its own test with an env flag
# rather than by a script.
echo "==> UPDATE_CONFORMANCE_BASELINE=1 cargo test -p labwired-core --test chip_conformance"
UPDATE_CONFORMANCE_BASELINE=1 cargo test -q -p labwired-core --test chip_conformance >/dev/null

# Same arrangement for the bus-visibility board (which chips' I2C/SPI/UART the
# logic analyzer can actually see).
#
# ⚠️ Both of these lines re-record a RATCHET baseline. Running this script turns
# a regression — a chip that LOST a bus, a reg-match count that fell — into a
# quiet diff instead of a red test. Read the resulting `git diff` on
# docs/coverage/ before committing; a ✓ that became a — is never routine.
echo "==> UPDATE_BUS_VISIBILITY_BASELINE=1 cargo test -p labwired-core --test bus_visibility"
UPDATE_BUS_VISIBILITY_BASELINE=1 cargo test -q -p labwired-core --test bus_visibility >/dev/null

echo
echo "All generated artifacts refreshed."
echo "If 'git status' is not clean, a committed artifact was stale — commit the result."
