[platformio]
src_dir = ../../examples/marketplace-arduino-c3/src
boards_dir = ../esp32c3-display-workshop/boards

[env:marketplace]
platform = espressif32@7.0.1
board = esp32-c3-supermini
framework = arduino
monitor_speed = 115200
