#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Assemble a secure-boot smoke script from packages + digests + system path."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# Seed-stable goldens (nRF52 TRNG seed 0xC0DEF00D) — independent of OEM key.
STATIC_ASSERTIONS = r"""
assertions:
  # ── UART narrative: all three boots, in story order ─────────────────────
  - uart_contains: "ROT: PROVISIONED"
  - uart_contains: "SECURE BOOT OK (v1)"
  - uart_contains: "OTA v2 SIGNATURE OK"
  - uart_contains: "OTA v2 COMMITTED"
  - uart_contains: "SECURE BOOT OK (v2)"
  - uart_contains: "ANTI-ROLLBACK v2 ACTIVE"
  - uart_contains: "ROLLBACK REJECTED"
  - uart_contains: "BAD SIGNATURE REJECTED"
  - uart_contains: "ATTESTATION OK"
  - uart_contains: "UPDATE SLOT VERIFIED"

  # ── Lifecycle state ──────────────────────────────────────────────────────
  - memory_value:
      address: 0x20000030 # BOOT_PHASE
      expected_value: 3
      size: 4
  - memory_value:
      address: 0x20000034 # INSTALLED_VERSION
      expected_value: 2
      size: 4
  - memory_value:
      address: 0x20000028 # ROLLBACK_COUNTER (v1+v2 burned, one-way)
      expected_value: 0xFFFFFFFC
      size: 4
  - memory_value:
      address: 0x20000024 # APPROTECT_READBACK (0 = Protected)
      expected_value: 0
      size: 4

  # ── Verdicts: verify, accept, both rejects, attestation ─────────────────
  - memory_value:
      address: 0x20000040 # VERIFY_RESULT
      expected_value: 1
      size: 4
  - memory_value:
      address: 0x2000003c # TAMPER_REJECT_RESULT
      expected_value: 1
      size: 4
  - memory_value:
      address: 0x20000000 # OTA_ACCEPTED (.uninit, survives boot-3 reboot)
      expected_value: 1
      size: 4
  - memory_value:
      address: 0x20000038 # ROLLBACK_REJECTED
      expected_value: 1
      size: 4
  - memory_value:
      address: 0x2000002c # BADSIG_REJECTED
      expected_value: 1
      size: 4
  - memory_value:
      address: 0x20000044 # ATTESTATION_OK
      expected_value: 1
      size: 4

  # ── The provisioned key, as read back from UICR ──────────────────────────
  - memory_value:
      address: 0x20000058 # KEY_WORDS[0]
      expected_value: 0x3FB3CA22
      size: 4
  - memory_value:
      address: 0x2000005c # KEY_WORDS[1]
      expected_value: 0xF2A23002
      size: 4
  - memory_value:
      address: 0x20000060 # KEY_WORDS[2]
      expected_value: 0x8AF7EE0B
      size: 4
  - memory_value:
      address: 0x20000064 # KEY_WORDS[3]
      expected_value: 0x56B76331
      size: 4

  # ── Real AES-128-ECB boot ciphertext from the ECB coprocessor ────────────
  - memory_value:
      address: 0x20000048 # CIPHERTEXT[0]
      expected_value: 0x62BBEEF9
      size: 4
  - memory_value:
      address: 0x2000004c # CIPHERTEXT[1]
      expected_value: 0xB81E39D1
      size: 4
  - memory_value:
      address: 0x20000050 # CIPHERTEXT[2]
      expected_value: 0xED88F1BF
      size: 4
  - memory_value:
      address: 0x20000054 # CIPHERTEXT[3]
      expected_value: 0x029C24B8
      size: 4
"""


def mem_block(title: str, base: int, words: list[str]) -> str:
    lines = [f"  # ── {title} ──"]
    for i, w in enumerate(words):
        addr = base + i * 4
        lines.append("  - memory_value:")
        lines.append(f"      address: 0x{addr:08X}")
        lines.append(f"      expected_value: {w}")
        lines.append("      size: 4")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--packages", type=Path, required=True)
    ap.add_argument("--digests", type=Path, required=True)
    ap.add_argument("--system", type=Path, required=True, help="path written into smoke inputs.system")
    ap.add_argument("--firmware", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    digests = json.loads(args.digests.read_text())
    packages = args.packages.read_text().rstrip() + "\n"
    header = f"""schema_version: "1.2"
# Generated by assemble_smoke.py — do not hand-edit package bytes.
# OEM signing key was ephemeral or external; only public verify material is retained.
inputs:
  system: "{args.system}"
  firmware: "{args.firmware}"
limits:
  max_steps: 30000000

"""
    body = (
        header
        + packages
        + "\n"
        + STATIC_ASSERTIONS.lstrip()
        + "\n"
        + mem_block(
            "The SHA-256 digest the firmware computed and the SE verified",
            0x20000004,
            digests["v2_header_payload_sha256_words_be"],
        )
        + "\n"
        + mem_block(
            "The committed update, read back from the flash slot in boot 3",
            0x20000068,
            digests["v2_payload_sha256_words_be"],
        )
        + "\n\n  - expected_stop_reason: max_steps\n"
    )
    args.out.write_text(body)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
