// AUTO-GENERATED by scripts/gen_embedded_descriptors.py — do not edit by hand.
// Embeds every configs/peripherals/**/*.yaml so SystemBus::from_config can
// resolve declarative descriptors WITHOUT a filesystem (wasm32 has no
// std::fs). Native builds still fall back to from_file for any path not
// embedded here. Keyed by the suffix after 'peripherals/'.
//
// Refresh: python3 scripts/gen_embedded_descriptors.py
// Guard: the embedded_descriptor_registry_is_complete test (native) fails
// when a descriptor exists on disk but is missing here.

/// Look up an embedded descriptor by its chip-YAML `path:` value
/// (e.g. `../peripherals/esp32c3/gpio.yaml`). Returns the YAML text if embedded.
pub fn lookup(descriptor_path: &str) -> Option<&'static str> {
    // Normalize: take everything after the last "peripherals/".
    let key = descriptor_path
        .rsplit_once("peripherals/")
        .map(|(_, k)| k)
        .unwrap_or(descriptor_path);
    match key {
        "esp32c3/aes.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/aes.yaml"
        )),
        "esp32c3/apb_ctrl.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/apb_ctrl.yaml"
        )),
        "esp32c3/apb_saradc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/apb_saradc.yaml"
        )),
        "esp32c3/assist_debug.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/assist_debug.yaml"
        )),
        "esp32c3/bb.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/bb.yaml"
        )),
        "esp32c3/dma.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/dma.yaml"
        )),
        "esp32c3/ds.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/ds.yaml"
        )),
        "esp32c3/efuse.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/efuse.yaml"
        )),
        "esp32c3/extmem.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/extmem.yaml"
        )),
        "esp32c3/gpio.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/gpio.yaml"
        )),
        "esp32c3/gpio_sd.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/gpio_sd.yaml"
        )),
        "esp32c3/hmac.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/hmac.yaml"
        )),
        "esp32c3/i2c0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/i2c0.yaml"
        )),
        "esp32c3/i2s0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/i2s0.yaml"
        )),
        "esp32c3/interrupt_core0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/interrupt_core0.yaml"
        )),
        "esp32c3/io_mux.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/io_mux.yaml"
        )),
        "esp32c3/ledc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/ledc.yaml"
        )),
        "esp32c3/radio_fe.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/radio_fe.yaml"
        )),
        "esp32c3/radio_nrx.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/radio_nrx.yaml"
        )),
        "esp32c3/rmt.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/rmt.yaml"
        )),
        "esp32c3/rng.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/rng.yaml"
        )),
        "esp32c3/rom.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/rom.yaml"
        )),
        "esp32c3/rsa.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/rsa.yaml"
        )),
        "esp32c3/rtc_cntl.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/rtc_cntl.yaml"
        )),
        "esp32c3/sensitive.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/sensitive.yaml"
        )),
        "esp32c3/sha.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/sha.yaml"
        )),
        "esp32c3/spi0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/spi0.yaml"
        )),
        "esp32c3/spi1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/spi1.yaml"
        )),
        "esp32c3/spi2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/spi2.yaml"
        )),
        "esp32c3/system.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/system.yaml"
        )),
        "esp32c3/systimer.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/systimer.yaml"
        )),
        "esp32c3/timg0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/timg0.yaml"
        )),
        "esp32c3/timg1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/timg1.yaml"
        )),
        "esp32c3/twai0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/twai0.yaml"
        )),
        "esp32c3/uart0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/uart0.yaml"
        )),
        "esp32c3/uart1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/uart1.yaml"
        )),
        "esp32c3/uhci0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/uhci0.yaml"
        )),
        "esp32c3/uhci1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/uhci1.yaml"
        )),
        "esp32c3/usb_device.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/usb_device.yaml"
        )),
        "esp32c3/wifi_mac.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/wifi_mac.yaml"
        )),
        "esp32c3/xts_aes.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32c3/xts_aes.yaml"
        )),
        "esp32s3/gpio.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32s3/gpio.yaml"
        )),
        "esp32s3/interrupt_core0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32s3/interrupt_core0.yaml"
        )),
        "esp32s3/timg0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/esp32s3/timg0.yaml"
        )),
        "mkw41z4/gpioa.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/gpioa.yaml"
        )),
        "mkw41z4/gpiob.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/gpiob.yaml"
        )),
        "mkw41z4/gpioc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/gpioc.yaml"
        )),
        "mkw41z4/i2c0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/i2c0.yaml"
        )),
        "mkw41z4/lpuart0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/lpuart0.yaml"
        )),
        "mkw41z4/mcg.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/mcg.yaml"
        )),
        "mkw41z4/pit.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/pit.yaml"
        )),
        "mkw41z4/pmc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/pmc.yaml"
        )),
        "mkw41z4/porta.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/porta.yaml"
        )),
        "mkw41z4/portb.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/portb.yaml"
        )),
        "mkw41z4/portc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/portc.yaml"
        )),
        "mkw41z4/rcm.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/rcm.yaml"
        )),
        "mkw41z4/sim.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/sim.yaml"
        )),
        "mkw41z4/smc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/smc.yaml"
        )),
        "mkw41z4/spi0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/spi0.yaml"
        )),
        "mkw41z4/tpm0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/tpm0.yaml"
        )),
        "mkw41z4/trng0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/mkw41z4/trng0.yaml"
        )),
        "nrf52832/aar.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/aar.yaml"
        )),
        "nrf52832/bprot.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/bprot.yaml"
        )),
        "nrf52832/ccm.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/ccm.yaml"
        )),
        "nrf52832/clock.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/clock.yaml"
        )),
        "nrf52832/comp.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/comp.yaml"
        )),
        "nrf52832/ecb.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/ecb.yaml"
        )),
        "nrf52832/egu0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/egu0.yaml"
        )),
        "nrf52832/egu1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/egu1.yaml"
        )),
        "nrf52832/egu2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/egu2.yaml"
        )),
        "nrf52832/egu3.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/egu3.yaml"
        )),
        "nrf52832/egu4.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/egu4.yaml"
        )),
        "nrf52832/egu5.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/egu5.yaml"
        )),
        "nrf52832/ficr.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/ficr.yaml"
        )),
        "nrf52832/fpu.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/fpu.yaml"
        )),
        "nrf52832/gpiote.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/gpiote.yaml"
        )),
        "nrf52832/i2s.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/i2s.yaml"
        )),
        "nrf52832/lpcomp.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/lpcomp.yaml"
        )),
        "nrf52832/mwu.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/mwu.yaml"
        )),
        "nrf52832/nfct.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/nfct.yaml"
        )),
        "nrf52832/nvmc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/nvmc.yaml"
        )),
        "nrf52832/p0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/p0.yaml"
        )),
        "nrf52832/pdm.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/pdm.yaml"
        )),
        "nrf52832/power.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/power.yaml"
        )),
        "nrf52832/ppi.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/ppi.yaml"
        )),
        "nrf52832/pwm0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/pwm0.yaml"
        )),
        "nrf52832/pwm1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/pwm1.yaml"
        )),
        "nrf52832/pwm2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/pwm2.yaml"
        )),
        "nrf52832/qdec.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/qdec.yaml"
        )),
        "nrf52832/radio.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/radio.yaml"
        )),
        "nrf52832/rng.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/rng.yaml"
        )),
        "nrf52832/rtc0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/rtc0.yaml"
        )),
        "nrf52832/rtc1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/rtc1.yaml"
        )),
        "nrf52832/rtc2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/rtc2.yaml"
        )),
        "nrf52832/saadc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/saadc.yaml"
        )),
        "nrf52832/spi0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spi0.yaml"
        )),
        "nrf52832/spi1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spi1.yaml"
        )),
        "nrf52832/spi2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spi2.yaml"
        )),
        "nrf52832/spim0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spim0.yaml"
        )),
        "nrf52832/spim1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spim1.yaml"
        )),
        "nrf52832/spim2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spim2.yaml"
        )),
        "nrf52832/spis0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spis0.yaml"
        )),
        "nrf52832/spis1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spis1.yaml"
        )),
        "nrf52832/spis2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/spis2.yaml"
        )),
        "nrf52832/swi0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/swi0.yaml"
        )),
        "nrf52832/swi1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/swi1.yaml"
        )),
        "nrf52832/swi2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/swi2.yaml"
        )),
        "nrf52832/swi3.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/swi3.yaml"
        )),
        "nrf52832/swi4.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/swi4.yaml"
        )),
        "nrf52832/swi5.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/swi5.yaml"
        )),
        "nrf52832/temp.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/temp.yaml"
        )),
        "nrf52832/timer0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/timer0.yaml"
        )),
        "nrf52832/timer1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/timer1.yaml"
        )),
        "nrf52832/timer2.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/timer2.yaml"
        )),
        "nrf52832/timer3.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/timer3.yaml"
        )),
        "nrf52832/timer4.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/timer4.yaml"
        )),
        "nrf52832/twi0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/twi0.yaml"
        )),
        "nrf52832/twi1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/twi1.yaml"
        )),
        "nrf52832/twim0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/twim0.yaml"
        )),
        "nrf52832/twim1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/twim1.yaml"
        )),
        "nrf52832/twis0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/twis0.yaml"
        )),
        "nrf52832/twis1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/twis1.yaml"
        )),
        "nrf52832/uart0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/uart0.yaml"
        )),
        "nrf52832/uarte0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/uarte0.yaml"
        )),
        "nrf52832/uicr.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/uicr.yaml"
        )),
        "nrf52832/wdt.yaml" => Some(include_str!(
            "../../../../configs/peripherals/nrf52832/wdt.yaml"
        )),
        "rp2040/adc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/adc.yaml"
        )),
        "rp2040/busctrl.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/busctrl.yaml"
        )),
        "rp2040/clocks.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/clocks.yaml"
        )),
        "rp2040/dma.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/dma.yaml"
        )),
        "rp2040/i2c0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/i2c0.yaml"
        )),
        "rp2040/i2c1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/i2c1.yaml"
        )),
        "rp2040/io_bank0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/io_bank0.yaml"
        )),
        "rp2040/io_qspi.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/io_qspi.yaml"
        )),
        "rp2040/pads_bank0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/pads_bank0.yaml"
        )),
        "rp2040/pads_qspi.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/pads_qspi.yaml"
        )),
        "rp2040/pio0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/pio0.yaml"
        )),
        "rp2040/pio1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/pio1.yaml"
        )),
        "rp2040/pll_sys.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/pll_sys.yaml"
        )),
        "rp2040/pll_usb.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/pll_usb.yaml"
        )),
        "rp2040/ppb.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/ppb.yaml"
        )),
        "rp2040/psm.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/psm.yaml"
        )),
        "rp2040/pwm.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/pwm.yaml"
        )),
        "rp2040/resets.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/resets.yaml"
        )),
        "rp2040/rosc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/rosc.yaml"
        )),
        "rp2040/rtc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/rtc.yaml"
        )),
        "rp2040/sio.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/sio.yaml"
        )),
        "rp2040/spare_irq.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/spare_irq.yaml"
        )),
        "rp2040/spi0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/spi0.yaml"
        )),
        "rp2040/spi1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/spi1.yaml"
        )),
        "rp2040/ssi.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/ssi.yaml"
        )),
        "rp2040/syscfg.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/syscfg.yaml"
        )),
        "rp2040/sysinfo.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/sysinfo.yaml"
        )),
        "rp2040/tbman.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/tbman.yaml"
        )),
        "rp2040/timer.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/timer.yaml"
        )),
        "rp2040/uart0.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/uart0.yaml"
        )),
        "rp2040/uart1.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/uart1.yaml"
        )),
        "rp2040/usb.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/usb.yaml"
        )),
        "rp2040/usb_dpram.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/usb_dpram.yaml"
        )),
        "rp2040/vreg_and_chip_reset.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/vreg_and_chip_reset.yaml"
        )),
        "rp2040/watchdog.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/watchdog.yaml"
        )),
        "rp2040/xip_ctrl.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/xip_ctrl.yaml"
        )),
        "rp2040/xosc.yaml" => Some(include_str!(
            "../../../../configs/peripherals/rp2040/xosc.yaml"
        )),
        "tmp102.yaml" => Some(include_str!("../../../../configs/peripherals/tmp102.yaml")),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::lookup;

    /// Every descriptor on disk must be embedded: a miss compiles fine and
    /// runs fine natively, then breaks ONLY in the browser on the lab that
    /// needs it. Regenerate with scripts/gen_embedded_descriptors.py.
    #[test]
    fn embedded_descriptor_registry_is_complete() {
        let root =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../configs/peripherals");
        let mut missing = Vec::new();
        let mut stack = vec![root.clone()];
        while let Some(dir) = stack.pop() {
            for entry in std::fs::read_dir(&dir).expect("read configs/peripherals") {
                let path = entry.expect("dir entry").path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|e| e == "yaml") {
                    let key = path
                        .strip_prefix(&root)
                        .expect("under peripherals root")
                        .to_string_lossy()
                        .into_owned();
                    if lookup(&key).is_none() {
                        missing.push(key);
                    }
                }
            }
        }
        missing.sort();
        assert!(
            missing.is_empty(),
            "descriptors on disk but not embedded (breaks wasm labs): {missing:?}\n\
             run: python3 scripts/gen_embedded_descriptors.py"
        );
    }
}
